// Generated from: featureFiles/PremiumUserRecordData/FoodIntakePremiumUser.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Food Intake Validation in the premium user record data', () => {

  test.beforeEach('Background: User is in Home Page after logged in', async ({ Given, When, pages }, testInfo) => { if (testInfo.error) return;
    await Given('User is in Home Page', null, { pages }); 
    await When('User clicks Food Intake', null, { pages }); 
  });
  
  test.describe('Verify Food Intake title and subtext', () => {

    test('Example #1', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Food Intake Tracker" for "Title" on the food intake form', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Track what you eat to manage your diabetes better" for "Subtext" on the food intake form', null, { pages }); 
    });

  });

  test('Verify presence of four tabs in food intake', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_02', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see following meal tabs in food intake form', {"dataTable":{"rows":[{"cells":[{"value":"Tab"}]},{"cells":[{"value":"Breakfast"}]},{"cells":[{"value":"Lunch"}]},{"cells":[{"value":"Dinner"}]},{"cells":[{"value":"Snack"}]}]}}, { pages }); 
  });

  test('Verify fields in Food Intake form', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_03', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following fields in the food intake form', {"dataTable":{"rows":[{"cells":[{"value":"Field"}]},{"cells":[{"value":"Food Name"}]},{"cells":[{"value":"Serving Size"}]},{"cells":[{"value":"Calories"}]},{"cells":[{"value":"Date"}]},{"cells":[{"value":"Notes"}]}]}}, { pages }); 
  });

  test('Verify Food Name field placeholder', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_04', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see "Food Name" field with placeholder "e.g., Grilled Chicken Salad"', null, { pages }); 
  });

  test('Verify the presense of dropdown for serving size', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_05', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see Serving Size dropdown options in food intake form', {"dataTable":{"rows":[{"cells":[{"value":"Options"}]},{"cells":[{"value":"Small (1/2 cup)"}]},{"cells":[{"value":"Medium (1 cup)"}]},{"cells":[{"value":"Large (2 cups)"}]},{"cells":[{"value":"Custom..."}]}]}}, { pages }); 
  });

  test('Verify Serving Size default value', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_06', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see  "Medium (1 cup)" as the default value in the Serving Size dropdown', null, { pages }); 
  });

  test('Verify the presence calculator icon in calorie', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_07', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see calculator icon in calorie', null, { pages }); 
  });

  test('Verify the placeholder text for calorie', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_08', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see "Calories" field with placeholder "e.g., 250"', null, { pages }); 
  });

  test('Verify helper text below Calories field', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_09', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see helper text "Enter calories or click the calculator icon for automatic calculation." below calorie field', null, { pages }); 
  });

  test('Verify the presence of placeholder in notes blocks', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_10', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see "Notes" field with placeholder "Add any additional information..."', null, { pages }); 
  });

  test('Verify Date field default value', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_11', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see current date displayed in the date field', null, { pages }); 
  });

  test('Verify Save Food Entry button', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_12', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see Save Food Entry button', null, { pages }); 
  });

  test.describe('Verify user able to save food entry button with <Scenario>', () => {

    test('Verify user able to save food entry button with valid data', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_13', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in food Intake form', null, { pages }); 
      await When('User clicks save food entry button after entering "valid data"', null, { pages, testData }); 
      await Then('User should see "Food Entry is recorded" in food intake form', null, { pages }); 
    });

  });

  test.describe('Verify user able to save food entry button with <Scenario> data', () => {

    test('Verify user able to save food entry button with invalid data', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_14', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in food Intake form', null, { pages }); 
      await When('User clicks save food entry button after entering "invalid"', null, { pages, testData }); 
      await Then('User should see alert with message "Failed to save food intake" in food intake form', null, { pages }); 
    });

  });

  test('Verify custom field in serving size', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_15', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
    await When('User selects "custom" option in "Serving Size" dropdown', null, { pages }); 
    await Then('User should see new input field added below the serving field', null, { pages }); 
  });

  test.describe('Verify user error message for invalid value <Scenario> in food name', () => {

    test('Verify user error message for invalid value numbers in food name', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_16', '@FunctionalValidation', '@negative'] }, async ({ When, Then, pages, testData }) => { 
      await When('User enters invalid value "numbers" in "Food Name"', null, { pages, testData }); 
      await Then('User should see error message "Please enter valid food name" under food name field', null, { pages }); 
    });

    test('Verify user error message for invalid value special char in food name', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_16', '@FunctionalValidation', '@negative'] }, async ({ When, Then, pages, testData }) => { 
      await When('User enters invalid value "special char" in "Food Name"', null, { pages, testData }); 
      await Then('User should see error message "Please enter valid food name" under food name field', null, { pages }); 
    });

  });

  test.describe('Verify the presence of automatic calorie calculation in calorie field', () => {

    test('Example #1', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_17', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
      await When('User enters valid "Grilled Chicken Salad" in "Food Name" field', null, { pages }); 
      await Then('User should see "Calories" value for the food name calculated automatically', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_17', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
      await When('User enters valid "paneer Sandwich" in "Food Name" field', null, { pages }); 
      await Then('User should see "Calories" value for the food name calculated automatically', null, { pages }); 
    });

    test('Example #3', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_17', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
      await When('User enters valid "Fruit Bowl" in "Food Name" field', null, { pages }); 
      await Then('User should see "Calories" value for the food name calculated automatically', null, { pages }); 
    });

  });

  test.describe('Verify helper text after automatic calorie calculation', () => {

    test('Example #1', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_18', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
      await When('User enters valid "pizza" in "Food Name" field', null, { pages }); 
      await Then('User should see helper text "Calories calculated automatically. You can edit if needed." below calorie field', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_18', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
      await When('User enters valid "paneer Sandwich" in "Food Name" field', null, { pages }); 
      await Then('User should see helper text "Calories calculated automatically. You can edit if needed." below calorie field', null, { pages }); 
    });

    test('Example #3', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_18', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
      await When('User enters valid "Fruit Bowl" in "Food Name" field', null, { pages }); 
      await Then('User should see helper text "Calories calculated automatically. You can edit if needed." below calorie field', null, { pages }); 
    });

  });

  test('Verify user able to edit the calorie value after automatic calorie calculation', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_19', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
    await When('User edit calorie value after automatic calorie calculation', null, { pages }); 
    await Then('User should see edited value in automatic calorie value', null, { pages }); 
  });

  test('Verify user able to save food entry with null value in food name', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_20', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
    await When('User clicks the Save Food Entry button after leaving the "Food Name" field empty', null, { pages }); 
    await Then('User should see an error message indicating that the "Please fill out this field."', null, { pages }); 
  });

  test('Verify date picker opens on clicking date field', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_21', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Food Intake screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see date picker opened', null, { pages }); 
  });

  test('Verify today\'s date is highlighted in the date picker', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_22', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Food Intake screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see today\'s date highlighted', null, { pages }); 
  });

  test('Verify previous button is present in the date picker', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_23', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Food Intake screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see the Previous button in date', null, { pages }); 
  });

  test('Verify next button is present in the date picker', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_24', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Food Intake screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see the Next button in date', null, { pages }); 
  });

  test('Verify user receives error message for entering more than 250 words in notes', { tag: ['@sweetBalance', '@FoodIntake', '@premiumUserRecordData', '@FoodIntake_25', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
    await When('User clicks save food entry after more than 250 words in notes', null, { pages }); 
    await Then('User should see error message in alert', null, { pages }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles/PremiumUserRecordData/FoodIntakePremiumUser.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":13,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Food Intake Tracker\" for \"Title\" on the food intake form","stepMatchArguments":[{"group":{"start":16,"value":"\"Food Intake Tracker\"","children":[{"start":17,"value":"Food Intake Tracker","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":42,"value":"\"Title\"","children":[{"start":43,"value":"Title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":14,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Track what you eat to manage your diabetes better\" for \"Subtext\" on the food intake form","stepMatchArguments":[{"group":{"start":16,"value":"\"Track what you eat to manage your diabetes better\"","children":[{"start":17,"value":"Track what you eat to manage your diabetes better","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"\"Subtext\"","children":[{"start":73,"value":"Subtext","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":17,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_02","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":18,"keywordType":"Outcome","textWithKeyword":"Then User should see following meal tabs in food intake form","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":26,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_03","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then User should see the following fields in the food intake form","stepMatchArguments":[]}]},
  {"pwTestLine":31,"pickleLine":36,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Food Name\" field with placeholder \"e.g., Grilled Chicken Salad\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Food Name\"","children":[{"start":17,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"e.g., Grilled Chicken Salad\"","children":[{"start":52,"value":"e.g., Grilled Chicken Salad","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":35,"pickleLine":40,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then User should see Serving Size dropdown options in food intake form","stepMatchArguments":[]}]},
  {"pwTestLine":39,"pickleLine":49,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_06","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then User should see  \"Medium (1 cup)\" as the default value in the Serving Size dropdown","stepMatchArguments":[{"group":{"start":17,"value":"\"Medium (1 cup)\"","children":[{"start":18,"value":"Medium (1 cup)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":43,"pickleLine":53,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_07","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then User should see calculator icon in calorie","stepMatchArguments":[]}]},
  {"pwTestLine":47,"pickleLine":57,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_08","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Calories\" field with placeholder \"e.g., 250\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Calories\"","children":[{"start":17,"value":"Calories","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"\"e.g., 250\"","children":[{"start":51,"value":"e.g., 250","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":51,"pickleLine":61,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_09","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then User should see helper text \"Enter calories or click the calculator icon for automatic calculation.\" below calorie field","stepMatchArguments":[{"group":{"start":28,"value":"\"Enter calories or click the calculator icon for automatic calculation.\"","children":[{"start":29,"value":"Enter calories or click the calculator icon for automatic calculation.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":65,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_10","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Notes\" field with placeholder \"Add any additional information...\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Notes\"","children":[{"start":17,"value":"Notes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"\"Add any additional information...\"","children":[{"start":48,"value":"Add any additional information...","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":59,"pickleLine":69,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_11","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":70,"keywordType":"Outcome","textWithKeyword":"Then User should see current date displayed in the date field","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":73,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_12","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"Then User should see Save Food Entry button","stepMatchArguments":[]}]},
  {"pwTestLine":69,"pickleLine":84,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_13","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":70,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is in food Intake form","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User clicks save food entry button after entering \"valid data\"","stepMatchArguments":[{"group":{"start":50,"value":"\"valid data\"","children":[{"start":51,"value":"valid data","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Food Entry is recorded\" in food intake form","stepMatchArguments":[{"group":{"start":16,"value":"\"Food Entry is recorded\"","children":[{"start":17,"value":"Food Entry is recorded","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":79,"pickleLine":94,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_14","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":88,"keywordType":"Context","textWithKeyword":"Given User is in food Intake form","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":89,"keywordType":"Action","textWithKeyword":"When User clicks save food entry button after entering \"invalid\"","stepMatchArguments":[{"group":{"start":50,"value":"\"invalid\"","children":[{"start":51,"value":"invalid","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":90,"keywordType":"Outcome","textWithKeyword":"Then User should see alert with message \"Failed to save food intake\" in food intake form","stepMatchArguments":[{"group":{"start":35,"value":"\"Failed to save food intake\"","children":[{"start":36,"value":"Failed to save food intake","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":87,"pickleLine":98,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_15","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":99,"keywordType":"Action","textWithKeyword":"When User selects \"custom\" option in \"Serving Size\" dropdown","stepMatchArguments":[{"group":{"start":13,"value":"\"custom\"","children":[{"start":14,"value":"custom","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"\"Serving Size\"","children":[{"start":33,"value":"Serving Size","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":100,"keywordType":"Outcome","textWithKeyword":"Then User should see new input field added below the serving field","stepMatchArguments":[]}]},
  {"pwTestLine":94,"pickleLine":108,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_16","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":104,"keywordType":"Action","textWithKeyword":"When User enters invalid value \"numbers\" in \"Food Name\"","stepMatchArguments":[{"group":{"start":26,"value":"\"numbers\"","children":[{"start":27,"value":"numbers","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Food Name\"","children":[{"start":40,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":96,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then User should see error message \"Please enter valid food name\" under food name field","stepMatchArguments":[{"group":{"start":30,"value":"\"Please enter valid food name\"","children":[{"start":31,"value":"Please enter valid food name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":99,"pickleLine":109,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_16","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":100,"gherkinStepLine":104,"keywordType":"Action","textWithKeyword":"When User enters invalid value \"special char\" in \"Food Name\"","stepMatchArguments":[{"group":{"start":26,"value":"\"special char\"","children":[{"start":27,"value":"special char","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"Food Name\"","children":[{"start":45,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":101,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then User should see error message \"Please enter valid food name\" under food name field","stepMatchArguments":[{"group":{"start":30,"value":"\"Please enter valid food name\"","children":[{"start":31,"value":"Please enter valid food name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":108,"pickleLine":118,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_17","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":113,"keywordType":"Action","textWithKeyword":"When User enters valid \"Grilled Chicken Salad\" in \"Food Name\" field","stepMatchArguments":[{"group":{"start":18,"value":"\"Grilled Chicken Salad\"","children":[{"start":19,"value":"Grilled Chicken Salad","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Food Name\"","children":[{"start":46,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":110,"gherkinStepLine":114,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Calories\" value for the food name calculated automatically","stepMatchArguments":[{"group":{"start":16,"value":"\"Calories\"","children":[{"start":17,"value":"Calories","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":113,"pickleLine":119,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_17","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":114,"gherkinStepLine":113,"keywordType":"Action","textWithKeyword":"When User enters valid \"paneer Sandwich\" in \"Food Name\" field","stepMatchArguments":[{"group":{"start":18,"value":"\"paneer Sandwich\"","children":[{"start":19,"value":"paneer Sandwich","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Food Name\"","children":[{"start":40,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":115,"gherkinStepLine":114,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Calories\" value for the food name calculated automatically","stepMatchArguments":[{"group":{"start":16,"value":"\"Calories\"","children":[{"start":17,"value":"Calories","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":118,"pickleLine":120,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_17","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":113,"keywordType":"Action","textWithKeyword":"When User enters valid \"Fruit Bowl\" in \"Food Name\" field","stepMatchArguments":[{"group":{"start":18,"value":"\"Fruit Bowl\"","children":[{"start":19,"value":"Fruit Bowl","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"Food Name\"","children":[{"start":35,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":120,"gherkinStepLine":114,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Calories\" value for the food name calculated automatically","stepMatchArguments":[{"group":{"start":16,"value":"\"Calories\"","children":[{"start":17,"value":"Calories","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":127,"pickleLine":128,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_18","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":128,"gherkinStepLine":124,"keywordType":"Action","textWithKeyword":"When User enters valid \"pizza\" in \"Food Name\" field","stepMatchArguments":[{"group":{"start":18,"value":"\"pizza\"","children":[{"start":19,"value":"pizza","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":29,"value":"\"Food Name\"","children":[{"start":30,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":125,"keywordType":"Outcome","textWithKeyword":"Then User should see helper text \"Calories calculated automatically. You can edit if needed.\" below calorie field","stepMatchArguments":[{"group":{"start":28,"value":"\"Calories calculated automatically. You can edit if needed.\"","children":[{"start":29,"value":"Calories calculated automatically. You can edit if needed.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":132,"pickleLine":129,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_18","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":124,"keywordType":"Action","textWithKeyword":"When User enters valid \"paneer Sandwich\" in \"Food Name\" field","stepMatchArguments":[{"group":{"start":18,"value":"\"paneer Sandwich\"","children":[{"start":19,"value":"paneer Sandwich","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Food Name\"","children":[{"start":40,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":125,"keywordType":"Outcome","textWithKeyword":"Then User should see helper text \"Calories calculated automatically. You can edit if needed.\" below calorie field","stepMatchArguments":[{"group":{"start":28,"value":"\"Calories calculated automatically. You can edit if needed.\"","children":[{"start":29,"value":"Calories calculated automatically. You can edit if needed.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":137,"pickleLine":130,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_18","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":138,"gherkinStepLine":124,"keywordType":"Action","textWithKeyword":"When User enters valid \"Fruit Bowl\" in \"Food Name\" field","stepMatchArguments":[{"group":{"start":18,"value":"\"Fruit Bowl\"","children":[{"start":19,"value":"Fruit Bowl","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"Food Name\"","children":[{"start":35,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":139,"gherkinStepLine":125,"keywordType":"Outcome","textWithKeyword":"Then User should see helper text \"Calories calculated automatically. You can edit if needed.\" below calorie field","stepMatchArguments":[{"group":{"start":28,"value":"\"Calories calculated automatically. You can edit if needed.\"","children":[{"start":29,"value":"Calories calculated automatically. You can edit if needed.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":144,"pickleLine":133,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_19","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":134,"keywordType":"Action","textWithKeyword":"When User edit calorie value after automatic calorie calculation","stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":135,"keywordType":"Outcome","textWithKeyword":"Then User should see edited value in automatic calorie value","stepMatchArguments":[]}]},
  {"pwTestLine":149,"pickleLine":138,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_20","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":150,"gherkinStepLine":139,"keywordType":"Action","textWithKeyword":"When User clicks the Save Food Entry button after leaving the \"Food Name\" field empty","stepMatchArguments":[{"group":{"start":57,"value":"\"Food Name\"","children":[{"start":58,"value":"Food Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":151,"gherkinStepLine":140,"keywordType":"Outcome","textWithKeyword":"Then User should see an error message indicating that the \"Please fill out this field.\"","stepMatchArguments":[{"group":{"start":53,"value":"\"Please fill out this field.\"","children":[{"start":54,"value":"Please fill out this field.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":154,"pickleLine":143,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_21","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":155,"gherkinStepLine":144,"keywordType":"Context","textWithKeyword":"Given User is on the Food Intake screen","stepMatchArguments":[]},{"pwStepLine":156,"gherkinStepLine":145,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":157,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then User should see date picker opened","stepMatchArguments":[]}]},
  {"pwTestLine":160,"pickleLine":149,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_22","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":161,"gherkinStepLine":150,"keywordType":"Context","textWithKeyword":"Given User is on the Food Intake screen","stepMatchArguments":[]},{"pwStepLine":162,"gherkinStepLine":151,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":163,"gherkinStepLine":152,"keywordType":"Outcome","textWithKeyword":"Then User should see today's date highlighted","stepMatchArguments":[]}]},
  {"pwTestLine":166,"pickleLine":155,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_23","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":167,"gherkinStepLine":156,"keywordType":"Context","textWithKeyword":"Given User is on the Food Intake screen","stepMatchArguments":[]},{"pwStepLine":168,"gherkinStepLine":157,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":169,"gherkinStepLine":158,"keywordType":"Outcome","textWithKeyword":"Then User should see the Previous button in date","stepMatchArguments":[]}]},
  {"pwTestLine":172,"pickleLine":161,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_24","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":173,"gherkinStepLine":162,"keywordType":"Context","textWithKeyword":"Given User is on the Food Intake screen","stepMatchArguments":[]},{"pwStepLine":174,"gherkinStepLine":163,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":175,"gherkinStepLine":164,"keywordType":"Outcome","textWithKeyword":"Then User should see the Next button in date","stepMatchArguments":[]}]},
  {"pwTestLine":178,"pickleLine":167,"tags":["@sweetBalance","@FoodIntake","@premiumUserRecordData","@FoodIntake_25","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Food Intake","isBg":true,"stepMatchArguments":[]},{"pwStepLine":179,"gherkinStepLine":168,"keywordType":"Action","textWithKeyword":"When User clicks save food entry after more than 250 words in notes","stepMatchArguments":[{"group":{"start":44,"value":"250","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":180,"gherkinStepLine":169,"keywordType":"Outcome","textWithKeyword":"Then User should see error message in alert","stepMatchArguments":[]}]},
]; // bdd-data-end