// Generated from: featureFiles/PremiumUserRecordData/PhysicalActivityPremiumUser.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Validating physical activity functionality in the premium user record data', () => {

  test.beforeEach('Background: User is in Home Page after logged in', async ({ Given, When, pages }, testInfo) => { if (testInfo.error) return;
    await Given('User is in Home Page', null, { pages }); 
    await When('User clicks physical activity', null, { pages }); 
  });
  
  test.describe('Verify <Scenario> in physical activity form', () => {

    test('Verify title in physical activity form', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Physical Activity" "title" in physical activity form', null, { pages }); 
    });

    test('Verify subtext in physical activity form', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Track your fitness journey" "subtext" in physical activity form', null, { pages }); 
    });

  });

  test('Verify fields in the Physical Activity form', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_02', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following fields in Physical Activity', {"dataTable":{"rows":[{"cells":[{"value":"Field"}]},{"cells":[{"value":"Activity Type"}]},{"cells":[{"value":"Duration"}]},{"cells":[{"value":"Date"}]},{"cells":[{"value":"Intensity"}]}]}}, { pages }); 
  });

  test('Verify the presence of dropdown for Activity Type', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_03', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see  dropdown for activity type', null, { pages }); 
  });

  test('Verify dropdown options for Activity Type', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_04', '@UIValidation'] }, async ({ When, Then, pages }) => { 
    await When('User clicks activity type dropdown', null, { pages }); 
    await Then('User should see the following options in Activity Type dropdown', {"dataTable":{"rows":[{"cells":[{"value":"Walking"}]},{"cells":[{"value":"Running"}]},{"cells":[{"value":"Cycling"}]},{"cells":[{"value":"Weight Training"}]},{"cells":[{"value":"Yoga"}]},{"cells":[{"value":"HIIT"}]},{"cells":[{"value":"Other"}]}]}}, { pages }); 
  });

  test('Verify the presence input for Duration', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_05', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see input field for duration', null, { pages }); 
  });

  test('Verify the placeholder text for Duration', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_06', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see "30" in placeholder field', null, { pages }); 
  });

  test('Verify dropdown for duration options', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_07', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see drop down duration', null, { pages }); 
  });

  test('Verify dropdown options for Duration unit', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_08', '@UIValidation'] }, async ({ When, Then, pages }) => { 
    await When('user clicks the duration dropdown', null, { pages }); 
    await Then('User should see the following duration units', {"dataTable":{"rows":[{"cells":[{"value":"minutes"}]},{"cells":[{"value":"hours"}]}]}}, { pages }); 
  });

  test('Verify the date picker option', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_09', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see date picker in physical activity', null, { pages }); 
  });

  test('Verify intensity buttons', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_10', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following intensity options', {"dataTable":{"rows":[{"cells":[{"value":"Intensity"}]},{"cells":[{"value":"light"}]},{"cells":[{"value":"moderate"}]},{"cells":[{"value":"vigorous"}]}]}}, { pages }); 
  });

  test('Verify the save activity button', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_11', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see save activity button in physical activity', null, { pages }); 
  });

  test.describe('Verify user is able to save activity for <Scenario>', () => {

    test('Verify user is able to save activity for walking with duration in minutes', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "walking with duration in minutes"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for running with duration in minutes', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "running with duration in minutes"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for cycling with duration in minutes', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "cycling with duration in minutes"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for yoga with duration in minutes', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "yoga with duration in minutes"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for weight training with duration in minutes', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "weight training with duration in minutes"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for walking with duration in hours', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "walking with duration in hours"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for running with duration in hours', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "running with duration in hours"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for cycling with duration in hours', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "cycling with duration in hours"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for yoga with duration in hours', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "yoga with duration in hours"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for weight training with duration in hours', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "weight training with duration in hours"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for HIIT with duration in minutes', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "HIIT with duration in minutes"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

    test('Verify user is able to save activity for HIIT with duration in hours', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_12', '@FunctionalValidation', '@positive1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User clicks record save activity button after entering "HIIT with duration in hours"', null, { pages, testData }); 
      await Then('User should see "Your activity has been saved." in physical activity form', null, { pages }); 
    });

  });

  test.describe('Verify user is unable to enter <Scenario> duration value', () => {

    test('Verify user is unable to enter alphabetic duration value', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_13', '@FunctionalValidation', '@negative1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User enters an "alphabetic" value in the duration text field', null, { pages, testData }); 
      await Then('User should see the field remain blank', null, { pages }); 
    });

    test('Verify user is unable to enter special char duration value', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_13', '@FunctionalValidation', '@negative1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Physical Activity screen', null, { pages }); 
      await When('User enters an "special char" value in the duration text field', null, { pages, testData }); 
      await Then('User should see the field remain blank', null, { pages }); 
    });

  });

  test('Verify date picker can be opened', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_13', '@FunctionalValidation', '@run'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Physical Activity screen', null, { pages }); 
    await When('User clicks the date picker', null, { pages }); 
    await Then('User should see the date calendar', null, { pages }); 
  });

  test('Verify today\'s date is highlighted in the date picker', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_14', '@FunctionalValidation', '@run'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Physical Activity screen', null, { pages }); 
    await When('User clicks the date picker', null, { pages }); 
    await Then('User should see today\'s date highlighted', null, { pages }); 
  });

  test('Verify the presence of previous button in the date picker', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_15', '@FunctionalValidation', '@run'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Physical Activity screen', null, { pages }); 
    await When('User clicks the date picker', null, { pages }); 
    await Then('User should see the previous button in the date picker', null, { pages }); 
  });

  test('Verify the presence of next button in the date picker', { tag: ['@sweetBalance', '@PhysicalActivity', '@premiumUserRecordData', '@PhysicalActivity_16', '@FunctionalValidation', '@run'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Physical Activity screen', null, { pages }); 
    await When('User clicks the date picker', null, { pages }); 
    await Then('User should see the next button in the date picker', null, { pages }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles/PremiumUserRecordData/PhysicalActivityPremiumUser.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":14,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Physical Activity\" \"title\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Physical Activity\"","children":[{"start":17,"value":"Physical Activity","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":36,"value":"\"title\"","children":[{"start":37,"value":"title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":15,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Track your fitness journey\" \"subtext\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Track your fitness journey\"","children":[{"start":17,"value":"Track your fitness journey","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"subtext\"","children":[{"start":46,"value":"subtext","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":18,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_02","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then User should see the following fields in Physical Activity","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":28,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_03","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see  dropdown for activity type","stepMatchArguments":[]}]},
  {"pwTestLine":31,"pickleLine":32,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When User clicks activity type dropdown","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then User should see the following options in Activity Type dropdown","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":44,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then User should see input field for duration","stepMatchArguments":[]}]},
  {"pwTestLine":40,"pickleLine":48,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_06","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then User should see \"30\" in placeholder field","stepMatchArguments":[{"group":{"start":16,"value":"\"30\"","children":[{"start":17,"value":"30","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":44,"pickleLine":52,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_07","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then User should see drop down duration","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":56,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_08","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":49,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When user clicks the duration dropdown","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then User should see the following duration units","stepMatchArguments":[]}]},
  {"pwTestLine":53,"pickleLine":63,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_09","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"Then User should see date picker in physical activity","stepMatchArguments":[]}]},
  {"pwTestLine":57,"pickleLine":67,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_10","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then User should see the following intensity options","stepMatchArguments":[]}]},
  {"pwTestLine":61,"pickleLine":75,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_11","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"Then User should see save activity button in physical activity","stepMatchArguments":[]}]},
  {"pwTestLine":67,"pickleLine":87,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"walking with duration in minutes\"","stepMatchArguments":[{"group":{"start":55,"value":"\"walking with duration in minutes\"","children":[{"start":56,"value":"walking with duration in minutes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":73,"pickleLine":88,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"running with duration in minutes\"","stepMatchArguments":[{"group":{"start":55,"value":"\"running with duration in minutes\"","children":[{"start":56,"value":"running with duration in minutes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":79,"pickleLine":89,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"cycling with duration in minutes\"","stepMatchArguments":[{"group":{"start":55,"value":"\"cycling with duration in minutes\"","children":[{"start":56,"value":"cycling with duration in minutes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":85,"pickleLine":90,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":87,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"yoga with duration in minutes\"","stepMatchArguments":[{"group":{"start":55,"value":"\"yoga with duration in minutes\"","children":[{"start":56,"value":"yoga with duration in minutes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":91,"pickleLine":91,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":92,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":93,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"weight training with duration in minutes\"","stepMatchArguments":[{"group":{"start":55,"value":"\"weight training with duration in minutes\"","children":[{"start":56,"value":"weight training with duration in minutes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":97,"pickleLine":92,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":98,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"walking with duration in hours\"","stepMatchArguments":[{"group":{"start":55,"value":"\"walking with duration in hours\"","children":[{"start":56,"value":"walking with duration in hours","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":103,"pickleLine":93,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":104,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"running with duration in hours\"","stepMatchArguments":[{"group":{"start":55,"value":"\"running with duration in hours\"","children":[{"start":56,"value":"running with duration in hours","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":109,"pickleLine":94,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"cycling with duration in hours\"","stepMatchArguments":[{"group":{"start":55,"value":"\"cycling with duration in hours\"","children":[{"start":56,"value":"cycling with duration in hours","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":112,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":115,"pickleLine":95,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":116,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":117,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"yoga with duration in hours\"","stepMatchArguments":[{"group":{"start":55,"value":"\"yoga with duration in hours\"","children":[{"start":56,"value":"yoga with duration in hours","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":121,"pickleLine":96,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":122,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"weight training with duration in hours\"","stepMatchArguments":[{"group":{"start":55,"value":"\"weight training with duration in hours\"","children":[{"start":56,"value":"weight training with duration in hours","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":124,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":127,"pickleLine":97,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":128,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":129,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"HIIT with duration in minutes\"","stepMatchArguments":[{"group":{"start":55,"value":"\"HIIT with duration in minutes\"","children":[{"start":56,"value":"HIIT with duration in minutes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":130,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":133,"pickleLine":98,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_12","@FunctionalValidation","@positive1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":134,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":135,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When User clicks record save activity button after entering \"HIIT with duration in hours\"","stepMatchArguments":[{"group":{"start":55,"value":"\"HIIT with duration in hours\"","children":[{"start":56,"value":"HIIT with duration in hours","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your activity has been saved.\" in physical activity form","stepMatchArguments":[{"group":{"start":16,"value":"\"Your activity has been saved.\"","children":[{"start":17,"value":"Your activity has been saved.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":143,"pickleLine":111,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_13","@FunctionalValidation","@negative1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":103,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":104,"keywordType":"Action","textWithKeyword":"When User enters an \"alphabetic\" value in the duration text field","stepMatchArguments":[{"group":{"start":15,"value":"\"alphabetic\"","children":[{"start":16,"value":"alphabetic","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":146,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then User should see the field remain blank","stepMatchArguments":[]}]},
  {"pwTestLine":149,"pickleLine":112,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_13","@FunctionalValidation","@negative1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":150,"gherkinStepLine":103,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":104,"keywordType":"Action","textWithKeyword":"When User enters an \"special char\" value in the duration text field","stepMatchArguments":[{"group":{"start":15,"value":"\"special char\"","children":[{"start":16,"value":"special char","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":152,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then User should see the field remain blank","stepMatchArguments":[]}]},
  {"pwTestLine":157,"pickleLine":116,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_13","@FunctionalValidation","@run"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":158,"gherkinStepLine":118,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":159,"gherkinStepLine":119,"keywordType":"Action","textWithKeyword":"When User clicks the date picker","stepMatchArguments":[]},{"pwStepLine":160,"gherkinStepLine":120,"keywordType":"Outcome","textWithKeyword":"Then User should see the date calendar","stepMatchArguments":[]}]},
  {"pwTestLine":163,"pickleLine":123,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_14","@FunctionalValidation","@run"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":164,"gherkinStepLine":125,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":165,"gherkinStepLine":126,"keywordType":"Action","textWithKeyword":"When User clicks the date picker","stepMatchArguments":[]},{"pwStepLine":166,"gherkinStepLine":127,"keywordType":"Outcome","textWithKeyword":"Then User should see today's date highlighted","stepMatchArguments":[]}]},
  {"pwTestLine":169,"pickleLine":130,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_15","@FunctionalValidation","@run"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":170,"gherkinStepLine":132,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":171,"gherkinStepLine":133,"keywordType":"Action","textWithKeyword":"When User clicks the date picker","stepMatchArguments":[]},{"pwStepLine":172,"gherkinStepLine":134,"keywordType":"Outcome","textWithKeyword":"Then User should see the previous button in the date picker","stepMatchArguments":[]}]},
  {"pwTestLine":175,"pickleLine":137,"tags":["@sweetBalance","@PhysicalActivity","@premiumUserRecordData","@PhysicalActivity_16","@FunctionalValidation","@run"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks physical activity","isBg":true,"stepMatchArguments":[]},{"pwStepLine":176,"gherkinStepLine":139,"keywordType":"Context","textWithKeyword":"Given User is on the Physical Activity screen","stepMatchArguments":[]},{"pwStepLine":177,"gherkinStepLine":140,"keywordType":"Action","textWithKeyword":"When User clicks the date picker","stepMatchArguments":[]},{"pwStepLine":178,"gherkinStepLine":141,"keywordType":"Outcome","textWithKeyword":"Then User should see the next button in the date picker","stepMatchArguments":[]}]},
]; // bdd-data-end