// Generated from: featureFiles/PremiumUserRecordData/TrackGlucosePremiumUser.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Validating Track Glucose functionality in the premium user record data', () => {

  test.beforeEach('Background: User is in Home Page after logged in', async ({ Given, When, pages }, testInfo) => { if (testInfo.error) return;
    await Given('User is in Home Page', null, { pages }); 
    await When('User clicks Blood Glucose', null, { pages }); 
  });
  
  test.describe('Verify <Scenario> in blood glucose form', () => {

    test('Verify title in blood glucose form', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Track Glucose" Heading for "title"', null, { pages }); 
    });

    test('Verify subtext in blood glucose form', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Keep your health in check" Heading for "subtext"', null, { pages }); 
    });

  });

  test('Verify input field in blood glucose field', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see text field for blood glucose', null, { pages }); 
  });

  test('Verify the placeholder input in blood glucose field', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see text "Enter blood glucose level" blood glucose', null, { pages }); 
  });

  test('Verify the text in the input field', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see "mg/dL" level unit next to blood glucose field', null, { pages }); 
  });

  test('Verify the presence of transition fields in track glucose', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following transition labels:', {"dataTable":{"rows":[{"cells":[{"value":"Transition"}]},{"cells":[{"value":"Low"}]},{"cells":[{"value":"Normal"}]},{"cells":[{"value":"High"}]}]}}, { pages }); 
  });

  test.describe('Verify colors for <Transition> levels', () => {

    test('Verify colors for Low levels', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "rgb(220, 38, 38)" color for "Low"', null, { pages }); 
    });

    test('Verify colors for Normal levels', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "rgb(22, 163, 74)" color for "Normal"', null, { pages }); 
    });

    test('Verify colors for High levels', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "rgb(217, 119, 6)" color for "High"', null, { pages }); 
    });

  });

  test('Verify the four buttons below Reading Type', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following buttons:', {"dataTable":{"rows":[{"cells":[{"value":"Button"}]},{"cells":[{"value":"Fasting"}]},{"cells":[{"value":"Pre-meal"}]},{"cells":[{"value":"Post-meal"}]},{"cells":[{"value":"Bedtime"}]}]}}, { pages }); 
  });

  test('Verify the date picker option', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see date picker', null, { pages }); 
  });

  test('Verify the last reading details', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see last reading details', null, { pages }); 
  });

  test('Verify the record reading button', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see record reading button', null, { pages }); 
  });

  test('Verify date picker opens on clicking date field', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Blood Glucose screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see date picker opened', null, { pages }); 
  });

  test('Verify today\'s date is highlighted in the date picker', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Blood Glucose screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see today\'s date highlighted', null, { pages }); 
  });

  test('Verify previous button is present in the date picker', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Blood Glucose screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see the Previous button in date', null, { pages }); 
  });

  test('Verify next button is present in the date picker', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on the Blood Glucose screen'); 
    await When('User clicks on date field', null, { pages }); 
    await Then('User should see the Next button in date', null, { pages }); 
  });

  test.describe('Verify transition details for <Scenario> are highlighted', () => {

    test('Verify transition details for low value are highlighted', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "low value" in blood glucose', null, { pages, testData }); 
      await Then('User should see transition details highlights', null, { pages, testData }); 
    });

    test('Verify transition details for high value are highlighted', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "high value" in blood glucose', null, { pages, testData }); 
      await Then('User should see transition details highlights', null, { pages, testData }); 
    });

    test('Verify transition details for normal value are highlighted', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "normal value" in blood glucose', null, { pages, testData }); 
      await Then('User should see transition details highlights', null, { pages, testData }); 
    });

  });

  test.describe('Verify blood glucose <Scenario> with valid input', () => {

    test('Verify blood glucose Low fasting reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Low fasting reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Normal fasting reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Normal fasting reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose High fasting reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "High fasting reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Low pre-meal reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Low pre-meal reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Normal pre-meal reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Normal pre-meal reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose High pre-meal reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "High pre-meal reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Low post-meal reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Low post-meal reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Normal post-meal reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Normal post-meal reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose High post-meal reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "High post-meal reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Low bedtime reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Low bedtime reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose Normal bedtime reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "Normal bedtime reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

    test('Verify blood glucose High bedtime reading with valid input', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@positive'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User clicks record reading button after entering "High bedtime reading" valid details', null, { pages, testData }); 
      await Then('User should see "Reading successfully recorded!" in track glucose form', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> blood glucose input is rejected', () => {

    test('Verify Negative blood glucose input is rejected', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "Negative" in the blood glucose field', null, { pages, testData }); 
      await Then('User should see the blood glucose field remain blank', null, { pages }); 
    });

    test('Verify Zero blood glucose input is rejected', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "Zero" in the blood glucose field', null, { pages, testData }); 
      await Then('User should see the blood glucose field remain blank', null, { pages }); 
    });

    test('Verify alphabetic blood glucose input is rejected', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "alphabetic" in the blood glucose field', null, { pages, testData }); 
      await Then('User should see the blood glucose field remain blank', null, { pages }); 
    });

    test('Verify special char input blood glucose input is rejected', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "special char input" in the blood glucose field', null, { pages, testData }); 
      await Then('User should see the blood glucose field remain blank', null, { pages }); 
    });

    test('Verify decimal value blood glucose input is rejected', { tag: ['@sweetBalance', '@TrackGlucose', '@premiumUserRecordData', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on the Blood Glucose screen'); 
      await When('User enters "decimal value" in the blood glucose field', null, { pages, testData }); 
      await Then('User should see the blood glucose field remain blank', null, { pages }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles/PremiumUserRecordData/TrackGlucosePremiumUser.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":14,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Track Glucose\" Heading for \"title\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Track Glucose\"","children":[{"start":17,"value":"Track Glucose","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"title\"","children":[{"start":45,"value":"title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":15,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Keep your health in check\" Heading for \"subtext\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Keep your health in check\"","children":[{"start":17,"value":"Keep your health in check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"subtext\"","children":[{"start":57,"value":"subtext","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":18,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then User should see text field for blood glucose","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":22,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then User should see text \"Enter blood glucose level\" blood glucose","stepMatchArguments":[{"group":{"start":21,"value":"\"Enter blood glucose level\"","children":[{"start":22,"value":"Enter blood glucose level","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":31,"pickleLine":26,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then User should see \"mg/dL\" level unit next to blood glucose field","stepMatchArguments":[{"group":{"start":16,"value":"\"mg/dL\"","children":[{"start":17,"value":"mg/dL","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":35,"pickleLine":30,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"Then User should see the following transition labels:","stepMatchArguments":[]}]},
  {"pwTestLine":41,"pickleLine":43,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then User should see \"rgb(220, 38, 38)\" color for \"Low\"","stepMatchArguments":[{"group":{"start":16,"value":"\"rgb(220, 38, 38)\"","children":[{"start":17,"value":"rgb(220, 38, 38)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Low\"","children":[{"start":46,"value":"Low","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":45,"pickleLine":44,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then User should see \"rgb(22, 163, 74)\" color for \"Normal\"","stepMatchArguments":[{"group":{"start":16,"value":"\"rgb(22, 163, 74)\"","children":[{"start":17,"value":"rgb(22, 163, 74)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Normal\"","children":[{"start":46,"value":"Normal","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":45,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then User should see \"rgb(217, 119, 6)\" color for \"High\"","stepMatchArguments":[{"group":{"start":16,"value":"\"rgb(217, 119, 6)\"","children":[{"start":17,"value":"rgb(217, 119, 6)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"High\"","children":[{"start":46,"value":"High","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":48,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then User should see the following buttons:","stepMatchArguments":[]}]},
  {"pwTestLine":59,"pickleLine":57,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then User should see date picker","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":61,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then User should see last reading details","stepMatchArguments":[]}]},
  {"pwTestLine":67,"pickleLine":65,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then User should see record reading button","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":69,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then User should see date picker opened","stepMatchArguments":[]}]},
  {"pwTestLine":77,"pickleLine":75,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":76,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":77,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"Then User should see today's date highlighted","stepMatchArguments":[]}]},
  {"pwTestLine":83,"pickleLine":81,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":82,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":85,"gherkinStepLine":83,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":84,"keywordType":"Outcome","textWithKeyword":"Then User should see the Previous button in date","stepMatchArguments":[]}]},
  {"pwTestLine":89,"pickleLine":87,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":90,"gherkinStepLine":88,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":89,"keywordType":"Action","textWithKeyword":"When User clicks on date field","stepMatchArguments":[]},{"pwStepLine":92,"gherkinStepLine":90,"keywordType":"Outcome","textWithKeyword":"Then User should see the Next button in date","stepMatchArguments":[]}]},
  {"pwTestLine":97,"pickleLine":101,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":98,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When User enters \"low value\" in blood glucose","stepMatchArguments":[{"group":{"start":12,"value":"\"low value\"","children":[{"start":13,"value":"low value","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then User should see transition details highlights","stepMatchArguments":[]}]},
  {"pwTestLine":103,"pickleLine":102,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":104,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When User enters \"high value\" in blood glucose","stepMatchArguments":[{"group":{"start":12,"value":"\"high value\"","children":[{"start":13,"value":"high value","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then User should see transition details highlights","stepMatchArguments":[]}]},
  {"pwTestLine":109,"pickleLine":103,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When User enters \"normal value\" in blood glucose","stepMatchArguments":[{"group":{"start":12,"value":"\"normal value\"","children":[{"start":13,"value":"normal value","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":112,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then User should see transition details highlights","stepMatchArguments":[]}]},
  {"pwTestLine":119,"pickleLine":114,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":120,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":121,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Low fasting reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Low fasting reading\"","children":[{"start":50,"value":"Low fasting reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":122,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":125,"pickleLine":115,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":126,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":127,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Normal fasting reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Normal fasting reading\"","children":[{"start":50,"value":"Normal fasting reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":128,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":131,"pickleLine":116,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"High fasting reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"High fasting reading\"","children":[{"start":50,"value":"High fasting reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":137,"pickleLine":117,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":138,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":139,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Low pre-meal reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Low pre-meal reading\"","children":[{"start":50,"value":"Low pre-meal reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":140,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":143,"pickleLine":118,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Normal pre-meal reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Normal pre-meal reading\"","children":[{"start":50,"value":"Normal pre-meal reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":146,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":149,"pickleLine":119,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":150,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"High pre-meal reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"High pre-meal reading\"","children":[{"start":50,"value":"High pre-meal reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":152,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":155,"pickleLine":120,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":156,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":157,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Low post-meal reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Low post-meal reading\"","children":[{"start":50,"value":"Low post-meal reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":158,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":161,"pickleLine":121,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":162,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":163,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Normal post-meal reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Normal post-meal reading\"","children":[{"start":50,"value":"Normal post-meal reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":164,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":167,"pickleLine":122,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":168,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":169,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"High post-meal reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"High post-meal reading\"","children":[{"start":50,"value":"High post-meal reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":170,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":173,"pickleLine":123,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":174,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":175,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Low bedtime reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Low bedtime reading\"","children":[{"start":50,"value":"Low bedtime reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":176,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":179,"pickleLine":124,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":180,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":181,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"Normal bedtime reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"Normal bedtime reading\"","children":[{"start":50,"value":"Normal bedtime reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":182,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":185,"pickleLine":125,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":186,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":187,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When User clicks record reading button after entering \"High bedtime reading\" valid details","stepMatchArguments":[{"group":{"start":49,"value":"\"High bedtime reading\"","children":[{"start":50,"value":"High bedtime reading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":188,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Reading successfully recorded!\" in track glucose form","stepMatchArguments":[{"group":{"start":16,"value":"\"Reading successfully recorded!\"","children":[{"start":17,"value":"Reading successfully recorded!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":195,"pickleLine":136,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":196,"gherkinStepLine":130,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":197,"gherkinStepLine":131,"keywordType":"Action","textWithKeyword":"When User enters \"Negative\" in the blood glucose field","stepMatchArguments":[{"group":{"start":12,"value":"\"Negative\"","children":[{"start":13,"value":"Negative","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":198,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"Then User should see the blood glucose field remain blank","stepMatchArguments":[]}]},
  {"pwTestLine":201,"pickleLine":137,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":202,"gherkinStepLine":130,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":203,"gherkinStepLine":131,"keywordType":"Action","textWithKeyword":"When User enters \"Zero\" in the blood glucose field","stepMatchArguments":[{"group":{"start":12,"value":"\"Zero\"","children":[{"start":13,"value":"Zero","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":204,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"Then User should see the blood glucose field remain blank","stepMatchArguments":[]}]},
  {"pwTestLine":207,"pickleLine":138,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":208,"gherkinStepLine":130,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":209,"gherkinStepLine":131,"keywordType":"Action","textWithKeyword":"When User enters \"alphabetic\" in the blood glucose field","stepMatchArguments":[{"group":{"start":12,"value":"\"alphabetic\"","children":[{"start":13,"value":"alphabetic","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":210,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"Then User should see the blood glucose field remain blank","stepMatchArguments":[]}]},
  {"pwTestLine":213,"pickleLine":139,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":214,"gherkinStepLine":130,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":215,"gherkinStepLine":131,"keywordType":"Action","textWithKeyword":"When User enters \"special char input\" in the blood glucose field","stepMatchArguments":[{"group":{"start":12,"value":"\"special char input\"","children":[{"start":13,"value":"special char input","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":216,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"Then User should see the blood glucose field remain blank","stepMatchArguments":[]}]},
  {"pwTestLine":219,"pickleLine":140,"tags":["@sweetBalance","@TrackGlucose","@premiumUserRecordData","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Blood Glucose","isBg":true,"stepMatchArguments":[]},{"pwStepLine":220,"gherkinStepLine":130,"keywordType":"Context","textWithKeyword":"Given User is on the Blood Glucose screen","stepMatchArguments":[]},{"pwStepLine":221,"gherkinStepLine":131,"keywordType":"Action","textWithKeyword":"When User enters \"decimal value\" in the blood glucose field","stepMatchArguments":[{"group":{"start":12,"value":"\"decimal value\"","children":[{"start":13,"value":"decimal value","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":222,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"Then User should see the blood glucose field remain blank","stepMatchArguments":[]}]},
]; // bdd-data-end