// Generated from: featureFiles/OnboardingWithReport/Onboardingwithbloodreport-Modal.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Onboarding scenarios with blood report - Modal Total 15 Scenarios', () => {

  test.beforeEach('Background: User successfully completed profile setup', async ({ Given, When, excelHelpers, pages, testData }, testInfo) => { if (testInfo.error) return;
    await Given('User is on complete profile form page', null, { pages, testData }); 
    await When('User clicks create account button after filling all values to set up background', null, { excelHelpers, pages }); 
  });
  
  test('Verify navigation of blood report modal', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@navbloodreportmodal', '@WithReport_01'] }, async ({ When, Then, pages }) => { 
    await When('User clicks on Upload Blood Report button', null, { pages }); 
    await Then('User should navigate to blood report modal', null, { pages }); 
  });

  test('Verify upload box supports drag & drop', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@uploadbox', '@WithReport_02'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on blood report modal', null, { pages }); 
    await When('User hovers over the upload box', null, { pages }); 
    await Then('Upload box should show drag & drop interaction', null, { pages }); 
  });

  test.describe('Verify <Scenario> in blood report upload modal', () => {

    test('Verify supported file types (PDF) in blood report upload modal', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@pdfupload'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on blood report modal', null, { pages }); 
      await When('user uploads "Invalid file Text or Excel" file', null, { pages }); 
      await Then('User should see "Only PDF files are supported" outcome', null, { pages, testData }); 
    });

    test('Verify file size limit (10MB) in blood report upload modal', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@pdfupload'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on blood report modal', null, { pages }); 
      await When('user uploads "Invalid pdf over 10mb" file', null, { pages }); 
      await Then('User should see "File exceeds 10MB" outcome', null, { pages, testData }); 
    });

    test('Verify valid PDF file upload in blood report upload modal', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@pdfupload'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on blood report modal', null, { pages }); 
      await When('user uploads "Valid pdf file" file', null, { pages }); 
      await Then('User should see "processing percentage bar" outcome', null, { pages, testData }); 
    });

  });

  test('Verify Upload & Process button is enabled after valid upload', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@uploadandprocessbtnenabled', '@WithReport_06'] }, async ({ Given, When, Then, pages, testData }) => { 
    await Given('User is on blood report modal', null, { pages }); 
    await When('user just uploads "Valid pdf file"', null, { pages }); 
    await Then('User should see "enabled pload&Process button" outcome', null, { pages, testData }); 
  });

  test('Verify upload cancel button functionality', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@uploadboxcancel', '@WithReport_07'] }, async ({ Given, When, Then, pages, testData }) => { 
    await Given('User is on blood report modal', null, { pages }); 
    await When('User clicks Cancel in upload blood report page', null, { pages }); 
    await Then('User should see "modal closed and returned to previous screen" outcome', null, { pages, testData }); 
  });

  test.describe('Verify <Scenario> after clicking Upload&Process button', () => {

    test('Verify Upload & Process processes the file after clicking Upload&Process button', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@uploadmodalbehavior'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is on blood report modal', null, { pages }); 
      await When('user uploads "Valid pdf file" file', null, { pages }); 
      await Then('User should see "Report analysis" after processing', null, { pages }); 
    });

    test('Verify onboarding button in report analysis after clicking Upload&Process button', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@uploadmodalbehavior'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is on blood report modal', null, { pages }); 
      await When('user uploads "Valid pdf file" file', null, { pages }); 
      await Then('User should see "continue to onboarding button" after processing', null, { pages }); 
    });

  });

  test('Upload report and verify all sections are visible', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@reportanalysisfield', '@WithReport_10'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is on blood report modal', null, { pages }); 
    await When('user uploads "Valid pdf file" file', null, { pages }); 
    await Then('User should see the following sections:', {"dataTable":{"rows":[{"cells":[{"value":"Blood Test Results"}]},{"cells":[{"value":"Complete Blood Count"}]},{"cells":[{"value":"Medical Conditions"}]},{"cells":[{"value":"Abnormal Values"}]},{"cells":[{"value":"Recommendations"}]}]}}, { pages }); 
  });

  test.describe('Verify <Scenario> in report analysis', () => {

    test('Verify presence of text field in report analysis', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@formvalidationstep1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on report analysis', null, { pages }); 
      await When('User clicks Onboarding button', null, { pages }); 
      await Then('User should see "Enter your age,Enter height in cm (1-300), Enter weight in kg (1-500)" for step for onboarding with Blood report for "presence of text field"', null, { pages, testData }); 
    });

    test('Verify presence of dropdown in report analysis', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@formvalidationstep1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on report analysis', null, { pages }); 
      await When('User clicks Onboarding button', null, { pages }); 
      await Then('User should see "dropdown option for Gender field" for step for onboarding with Blood report for "presence of dropdown"', null, { pages, testData }); 
    });

    test('Verify progress bar is visible in report analysis', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@formvalidationstep1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on report analysis', null, { pages }); 
      await When('User clicks Onboarding button', null, { pages }); 
      await Then('User should see "Progress Bar" for step for onboarding with Blood report for "progress bar is visible"', null, { pages, testData }); 
    });

    test('Verify presence of continue button in report analysis', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@formvalidationstep1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on report analysis', null, { pages }); 
      await When('User clicks Onboarding button', null, { pages }); 
      await Then('User should see "Continue button is visible" for step for onboarding with Blood report for "presence of continue button"', null, { pages, testData }); 
    });

    test('Verify incomplete steps (2-5) are not highlighted in report analysis', { tag: ['@sweet', '@withreportmodal', '@skiplogin', '@formvalidationstep1'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is on report analysis', null, { pages }); 
      await When('User clicks Onboarding button', null, { pages }); 
      await Then('User should see "Steps 2 to 5 remain unhighlighted" for step for onboarding with Blood report for "incomplete steps (2-5) are not highlighted"', null, { pages, testData }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles/OnboardingWithReport/Onboardingwithbloodreport-Modal.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":12,"tags":["@sweet","@withreportmodal","@skiplogin","@navbloodreportmodal","@WithReport_01"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When User clicks on Upload Blood Report button","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then User should navigate to blood report modal","stepMatchArguments":[]}]},
  {"pwTestLine":16,"pickleLine":21,"tags":["@sweet","@withreportmodal","@skiplogin","@uploadbox","@WithReport_02"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":22,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When User hovers over the upload box","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then Upload box should show drag & drop interaction","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":34,"tags":["@sweet","@withreportmodal","@skiplogin","@pdfupload"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When user uploads \"Invalid file Text or Excel\" file","stepMatchArguments":[{"group":{"start":13,"value":"\"Invalid file Text or Excel\"","children":[{"start":14,"value":"Invalid file Text or Excel","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Only PDF files are supported\" outcome","stepMatchArguments":[{"group":{"start":16,"value":"\"Only PDF files are supported\"","children":[{"start":17,"value":"Only PDF files are supported","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":30,"pickleLine":35,"tags":["@sweet","@withreportmodal","@skiplogin","@pdfupload"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When user uploads \"Invalid pdf over 10mb\" file","stepMatchArguments":[{"group":{"start":13,"value":"\"Invalid pdf over 10mb\"","children":[{"start":14,"value":"Invalid pdf over 10mb","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then User should see \"File exceeds 10MB\" outcome","stepMatchArguments":[{"group":{"start":16,"value":"\"File exceeds 10MB\"","children":[{"start":17,"value":"File exceeds 10MB","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":36,"tags":["@sweet","@withreportmodal","@skiplogin","@pdfupload"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When user uploads \"Valid pdf file\" file","stepMatchArguments":[{"group":{"start":13,"value":"\"Valid pdf file\"","children":[{"start":14,"value":"Valid pdf file","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then User should see \"processing percentage bar\" outcome","stepMatchArguments":[{"group":{"start":16,"value":"\"processing percentage bar\"","children":[{"start":17,"value":"processing percentage bar","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":44,"pickleLine":39,"tags":["@sweet","@withreportmodal","@skiplogin","@uploadandprocessbtnenabled","@WithReport_06"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":40,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":41,"keywordType":"Action","textWithKeyword":"When user just uploads \"Valid pdf file\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Valid pdf file\"","children":[{"start":19,"value":"Valid pdf file","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then User should see \"enabled pload&Process button\" outcome","stepMatchArguments":[{"group":{"start":16,"value":"\"enabled pload&Process button\"","children":[{"start":17,"value":"enabled pload&Process button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":50,"pickleLine":45,"tags":["@sweet","@withreportmodal","@skiplogin","@uploadboxcancel","@WithReport_07"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":46,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"When User clicks Cancel in upload blood report page","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":48,"keywordType":"Outcome","textWithKeyword":"Then User should see \"modal closed and returned to previous screen\" outcome","stepMatchArguments":[{"group":{"start":16,"value":"\"modal closed and returned to previous screen\"","children":[{"start":17,"value":"modal closed and returned to previous screen","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":58,"pickleLine":58,"tags":["@sweet","@withreportmodal","@skiplogin","@uploadmodalbehavior"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":52,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When user uploads \"Valid pdf file\" file","stepMatchArguments":[{"group":{"start":13,"value":"\"Valid pdf file\"","children":[{"start":14,"value":"Valid pdf file","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Report analysis\" after processing","stepMatchArguments":[{"group":{"start":16,"value":"\"Report analysis\"","children":[{"start":17,"value":"Report analysis","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":64,"pickleLine":59,"tags":["@sweet","@withreportmodal","@skiplogin","@uploadmodalbehavior"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":52,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When user uploads \"Valid pdf file\" file","stepMatchArguments":[{"group":{"start":13,"value":"\"Valid pdf file\"","children":[{"start":14,"value":"Valid pdf file","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then User should see \"continue to onboarding button\" after processing","stepMatchArguments":[{"group":{"start":16,"value":"\"continue to onboarding button\"","children":[{"start":17,"value":"continue to onboarding button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":72,"pickleLine":62,"tags":["@sweet","@withreportmodal","@skiplogin","@reportanalysisfield","@WithReport_10"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":63,"keywordType":"Context","textWithKeyword":"Given User is on blood report modal","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When user uploads \"Valid pdf file\" file","stepMatchArguments":[{"group":{"start":13,"value":"\"Valid pdf file\"","children":[{"start":14,"value":"Valid pdf file","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then User should see the following sections:","stepMatchArguments":[]}]},
  {"pwTestLine":80,"pickleLine":84,"tags":["@sweet","@withreportmodal","@skiplogin","@formvalidationstep1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is on report analysis","stepMatchArguments":[]},{"pwStepLine":82,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Enter your age,Enter height in cm (1-300), Enter weight in kg (1-500)\" for step for onboarding with Blood report for \"presence of text field\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Enter your age,Enter height in cm (1-300), Enter weight in kg (1-500)\"","children":[{"start":17,"value":"Enter your age,Enter height in cm (1-300), Enter weight in kg (1-500)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":134,"value":"\"presence of text field\"","children":[{"start":135,"value":"presence of text field","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":86,"pickleLine":85,"tags":["@sweet","@withreportmodal","@skiplogin","@formvalidationstep1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":87,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is on report analysis","stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","stepMatchArguments":[]},{"pwStepLine":89,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see \"dropdown option for Gender field\" for step for onboarding with Blood report for \"presence of dropdown\"","stepMatchArguments":[{"group":{"start":16,"value":"\"dropdown option for Gender field\"","children":[{"start":17,"value":"dropdown option for Gender field","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":97,"value":"\"presence of dropdown\"","children":[{"start":98,"value":"presence of dropdown","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":92,"pickleLine":86,"tags":["@sweet","@withreportmodal","@skiplogin","@formvalidationstep1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":93,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is on report analysis","stepMatchArguments":[]},{"pwStepLine":94,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Progress Bar\" for step for onboarding with Blood report for \"progress bar is visible\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Progress Bar\"","children":[{"start":17,"value":"Progress Bar","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":77,"value":"\"progress bar is visible\"","children":[{"start":78,"value":"progress bar is visible","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":98,"pickleLine":87,"tags":["@sweet","@withreportmodal","@skiplogin","@formvalidationstep1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is on report analysis","stepMatchArguments":[]},{"pwStepLine":100,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Continue button is visible\" for step for onboarding with Blood report for \"presence of continue button\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Continue button is visible\"","children":[{"start":17,"value":"Continue button is visible","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":91,"value":"\"presence of continue button\"","children":[{"start":92,"value":"presence of continue button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":104,"pickleLine":88,"tags":["@sweet","@withreportmodal","@skiplogin","@formvalidationstep1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on complete profile form page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks create account button after filling all values to set up background","isBg":true,"stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is on report analysis","stepMatchArguments":[]},{"pwStepLine":106,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Steps 2 to 5 remain unhighlighted\" for step for onboarding with Blood report for \"incomplete steps (2-5) are not highlighted\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Steps 2 to 5 remain unhighlighted\"","children":[{"start":17,"value":"Steps 2 to 5 remain unhighlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":98,"value":"\"incomplete steps (2-5) are not highlighted\"","children":[{"start":99,"value":"incomplete steps (2-5) are not highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end