// Generated from: featureFiles\OnboardingWithReport\OnboardingWithBloodReport-Steps.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Onboarding scenarios with blood report - Steps Total 45 Scenarios', () => {

  test.beforeEach('Background: User is on step 1 of onboarding', async ({ Given, When, pages }, testInfo) => { if (testInfo.error) return;
    await Given('User is on report analysis and uploads the file', null, { pages }); 
    await When('User clicks Onboarding button', null, { pages }); 
  });
  
  test.describe('Verify presence of <Scenario> with report step 1', () => {

    test('Verify presence of step 1 title with report step 1', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1titleswithreport'] }, async ({ Then, pages }) => { 
      await Then('User should see "Help Us Help You (We Promise, No Long Forms!)" for "step 1 title" in steps', null, { pages }); 
    });

    test('Verify presence of step 1 subheading with report step 1', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1titleswithreport'] }, async ({ Then, pages }) => { 
      await Then('User should see "Help us understand your health better" for "step 1 subheading" in steps', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> in step 1 with report', () => {

    test('Verify step progress is highlighted in step 1 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@navbloodreportmodal', '@step1'] }, async ({ Then, pages }) => { 
      await Then('User should see "Step 1 indicator highlighted" for "step progress is highlighted" in step 1', null, { pages }); 
    });

    test('Verify progress shows 1 of 5 steps in step 1 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@navbloodreportmodal', '@step1'] }, async ({ Then, pages }) => { 
      await Then('User should see "Step 1 of 5" for "progress shows 1 of 5 steps" in step 1', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> functionality in step 1 with report', () => {

    test('Verify alphabets in height field functionality in step 1 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1fieldfn'] }, async ({ When, Then, browserName, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Please enter a number." for "alphabets in height field" for step 1 fields', null, { browserName, pages, testData }); 
    });

    test('Verify alphabets in weight field functionality in step 1 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1fieldfn'] }, async ({ When, Then, browserName, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Please enter a number." for "alphabets in weight field" for step 1 fields', null, { browserName, pages, testData }); 
    });

  });

  test.describe('Verify presence of <Scenario> with report step 2', () => {

    test('Verify presence of step 2 title with report step 2', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2titleswithreport'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Pick your pace: chill stroll or marathon magic" for "step 2 title" in steps', null, { pages }); 
    });

    test('Verify presence of step 2 subheading with report step 2', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2titleswithreport'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Select your preferred exercise intensity level" for "step 2 subheading" in steps', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> from step 1 to step 2 with report', () => {

    test('Verify step progress is highlighted from step 1 to step 2 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1tostep2withreport'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Step 2 indicator highlighted" for "step progress is highlighted" in step 2', null, { pages }); 
    });

    test('Verify navigation of step from step 1 to step 2 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1tostep2withreport'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Step 2 of 5" for "navigation of step" in step 2', null, { pages }); 
    });

    test('Verify progress shows 2 of 5 steps from step 1 to step 2 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1tostep2withreport'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Step 2 of 5" for "progress shows 2 of 5 steps" in step 2', null, { pages }); 
    });

    test('Verify Back button visibility from step 1 to step 2 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step1tostep2withreport'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
      await Then('User should see "Back" for "Back button visibility" in step 2', null, { pages }); 
    });

  });

  test('Verify presence of intensity level options in step 2', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2options', '@WithReportSteps_13'] }, async ({ When, Then, pages, testData }) => { 
    await When('User clicks continue after entering values in step 1', null, { pages, testData }); 
    await Then('User should see options:', {"dataTable":{"rows":[{"cells":[{"value":"Easy 🦋"}]},{"cells":[{"value":"Medium 💪"}]},{"cells":[{"value":"Hard 🔥"}]}]}}, { pages }); 
  });

  test.describe('Verify presence of <Scenario> with report step 3', () => {

    test('Verify presence of step 3 title with report step 3', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3titleswithreport'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see "Your taste buds—what team are they on?" for "step 3 title" in steps', null, { pages }); 
    });

    test('Verify presence of step 3 subheading with report step 3', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3titleswithreport'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see "Select your dietary preference" for "step 3 subheading" in steps', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> from step 2 to step 3 with report', () => {

    test('Verify option selection in step 2 from step 2 to step 3 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2tostep3'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Medium 💪" from step 2', null, { pages }); 
      await Then('User should see "Step 3 of 5" for "option selection in step 2" in step 3', null, { pages }); 
    });

    test('Verify step progress is highlighted from step 2 to step 3 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2tostep3'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see "Step 3 indicator highlighted" for "step progress is highlighted" in step 3', null, { pages }); 
    });

    test('Verify navigation of step from step 2 to step 3 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2tostep3'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see "Step 3 of 5" for "navigation of step" in step 3', null, { pages }); 
    });

    test('Verify progress shows 3 of 5 steps from step 2 to step 3 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2tostep3'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see "Step 3 of 5" for "progress shows 3 of 5 steps" in step 3', null, { pages }); 
    });

    test('Verify Back button visibility from step 2 to step 3 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step2tostep3'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see "Back" for "Back button visibility" in step 3', null, { pages }); 
    });

  });

  test.describe('Verify presence of diet options in step 3 after selecting <Option> in step 2', () => {

    test('Verify presence of diet options in step 3 after selecting Easy 🦋 in step 2', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3options'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Easy 🦋" from step 2', null, { pages }); 
      await Then('User should see options:', {"dataTable":{"rows":[{"cells":[{"value":"All-inclusive diet 🍴🍖🍎"}]},{"cells":[{"value":"Vegan 🥬🌱🌿"}]},{"cells":[{"value":"Vegetarian 🥗🍆🥕"}]}]}}, { pages }); 
    });

  });

  test('Verify navigation of back button in step 2 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@navbackstep2tostep1', '@WithReportSteps_22'] }, async ({ Given, When, Then, pages, testData }) => { 
    await Given('User is in step2 of onboarding with report', null, { pages, testData }); 
    await When('User clicks back button', null, { pages }); 
    await Then('User should see "Step 1 of 5" for "navigation of back button" in step 2', null, { pages }); 
  });

  test.describe('Verify presence of <Scenario> with report step 4', () => {

    test('Verify presence of step 4 title with report step 4', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4titleswithreport'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "All-inclusive diet 🍴🍖🍎" from step 3', null, { pages }); 
      await Then('User should see "What\'s your go-to food passport?" for "step 4 title" in steps', null, { pages }); 
    });

    test('Verify presence of step 4 subheading with report step 4', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4titleswithreport'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "All-inclusive diet 🍴🍖🍎" from step 3', null, { pages }); 
      await Then('User should see "To create a meal plan you\'ll enjoy, please select your preferred cuisines!" for "step 4 subheading" in steps', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> from step 3 to step 4 with report', () => {

    test('Verify option selection in step 3 from step 3 to step 4 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3tostep4'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Vegan 🥬🌱🌿" from step 3', null, { pages }); 
      await Then('User should see "Step 4 of 5" for "option selection in step 3" in step 4', null, { pages }); 
    });

    test('Verify step progress is highlighted from step 3 to step 4 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3tostep4'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Vegan 🥬🌱🌿" from step 3', null, { pages }); 
      await Then('User should see "Step 4 indicator highlighted" for "step progress is highlighted" in step 4', null, { pages }); 
    });

    test('Verify navigation of step from step 3 to step 4 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3tostep4'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Vegan 🥬🌱🌿" from step 3', null, { pages }); 
      await Then('User should see "Step 4 of 5" for "navigation of step" in step 4', null, { pages }); 
    });

    test('Verify progress shows 4 of 5 steps from step 3 to step 4 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3tostep4'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Vegan 🥬🌱🌿" from step 3', null, { pages }); 
      await Then('User should see "Step 4 of 5" for "progress shows 4 of 5 steps" in step 4', null, { pages }); 
    });

    test('Verify Back button visibility from step 3 to step 4 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step3tostep4'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Vegan 🥬🌱🌿" from step 3', null, { pages }); 
      await Then('User should see "Back" for "Back button visibility" in step 4', null, { pages }); 
    });

  });

  test.describe('Verify presence of cuisine options in step 4 after <DietOption> in step 3', () => {

    test('Verify presence of cuisine options in step 4 after All-inclusive diet 🍴🍖🍎 in step 3', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4options'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "All-inclusive diet 🍴🍖🍎" from step 3', null, { pages }); 
      await Then('User should see options:', {"dataTable":{"rows":[{"cells":[{"value":"Indian 🍛"}]},{"cells":[{"value":"American 🍔"}]},{"cells":[{"value":"Continental 🥖"}]},{"cells":[{"value":"Mediterranean 🥙"}]},{"cells":[{"value":"Asian 🍜"}]},{"cells":[{"value":"Middle Eastern 🥙"}]},{"cells":[{"value":"Mexican 🌮"}]}]}}, { pages }); 
    });

  });

  test('Verify navigation of back button in step 3 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@navbackstep3tostep2', '@WithReportSteps_31'] }, async ({ Given, When, Then, pages, testData }) => { 
    await Given('User is in step3 of onboarding with report', null, { pages, testData }); 
    await When('User clicks back button', null, { pages }); 
    await Then('User should see "Step 2 of 5" for "navigation of back button" in step 3', null, { pages }); 
  });

  test.describe('Verify presence of <Scenario> with report step 5', () => {

    test('Verify presence of step 5 title with report step 5', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step5titleswithreport'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Allergic to any foods?" for "step 5 title" in steps', null, { pages }); 
    });

    test('Verify presence of step 5 subheading with report step 5', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step5titleswithreport'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Select all that apply" for "step 5 subheading" in steps', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> from step 4 to step 5 with report', () => {

    test('Verify option selection in step 4 from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Step 5 of 5" for "option selection in step 4" in step 5', null, { pages }); 
    });

    test('Verify step progress is highlighted from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Step 5 indicator highlighted" for "step progress is highlighted" in step 5', null, { pages }); 
    });

    test('Verify navigation of step from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Step 5 of 5" for "navigation of step" in step 5', null, { pages }); 
    });

    test('Verify progress shows 5 of 5 steps from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Step 5 of 5" for "progress shows 5 of 5 steps" in step 5', null, { pages }); 
    });

    test('Verify Back button visibility from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Back" for "Back button visibility" in step 5', null, { pages }); 
    });

    test('Verify Submit button visibility from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Submit" for "Submit button visibility" in step 5', null, { pages }); 
    });

    test('Verify Checkbox for options from step 4 to step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step4tostep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Indian 🍛" from step 4', null, { pages }); 
      await Then('User should see "Check box" for "Checkbox for options" in step 5', null, { pages }); 
    });

  });

  test.describe('Verify presence of allergy options in step 5 after <CuisineOption> in step 4', () => {

    test('Verify presence of allergy options in step 5 after Asian 🍜 in step 4', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@step5options'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
      await When('User clicks "Asian 🍜" from step 4', null, { pages }); 
      await Then('User should see options:', {"dataTable":{"rows":[{"cells":[{"value":"Gluten 🥖🍞"}]},{"cells":[{"value":"Dairy 🐄🥛"}]},{"cells":[{"value":"Nuts 🌰🥜"}]},{"cells":[{"value":"Eggs 🍳🥚"}]},{"cells":[{"value":"Soy 🫘🥡"}]},{"cells":[{"value":"Shellfish 🐚🍤"}]},{"cells":[{"value":"Other 🍽️🥴"}]},{"cells":[{"value":"None"}]}]}}, { pages }); 
    });

  });

  test('Verify navigation of back button in step 4 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@navbackstep4tostep3', '@WithReportSteps_42'] }, async ({ Given, When, Then, pages, testData }) => { 
    await Given('User is in step4 of onboarding with report', null, { pages, testData }); 
    await When('User clicks back button', null, { pages }); 
    await Then('User should see "Step 3 of 5" for "navigation of back button" in step 4', null, { pages }); 
  });

  test('Verify navigation of back button in step 5 with report', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@navbackstep5tostep4', '@WithReportSteps_43'] }, async ({ Given, When, Then, pages, testData }) => { 
    await Given('User is in step5 of onboarding with report', null, { pages, testData }); 
    await When('User clicks back button', null, { pages }); 
    await Then('User should see "Step 4 of 5" for "navigation of back button" in step 5', null, { pages }); 
  });

  test.describe('Verify <Scenario> selection in allergy from step 5', () => {

    test('Verify Single selection in allergy from step 5', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@selectionstep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step5 of onboarding with report', null, { pages, testData }); 
      await When('User selects "Gluten 🥖🍞, Dairy 🐄🥛,  Nuts 🌰🥜" and clicks submit from step 5', null, { pages }); 
      await Then('User should be navigated to free and premium details page', null, { pages }); 
    });

    test('Verify Multiple selection in allergy from step 5', { tag: ['@sweet', '@withreportsteps', '@skiplogin', '@register', '@ela', '@selectionstep5'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in step5 of onboarding with report', null, { pages, testData }); 
      await When('User selects "Gluten 🥖🍞" and clicks submit from step 5', null, { pages }); 
      await Then('User should be navigated to free and premium details page', null, { pages }); 
    });

  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $runScenarioHooks, excelHelpers, pages, testData }) => $runScenarioHooks('before', { excelHelpers, pages, testData }));

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles\\OnboardingWithReport\\OnboardingWithBloodReport-Steps.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":17,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Help Us Help You (We Promise, No Long Forms!)\" for \"step 1 title\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Help Us Help You (We Promise, No Long Forms!)\"","children":[{"start":17,"value":"Help Us Help You (We Promise, No Long Forms!)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"step 1 title\"","children":[{"start":69,"value":"step 1 title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":18,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Help us understand your health better\" for \"step 1 subheading\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Help us understand your health better\"","children":[{"start":17,"value":"Help us understand your health better","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":60,"value":"\"step 1 subheading\"","children":[{"start":61,"value":"step 1 subheading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":25,"pickleLine":27,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@navbloodreportmodal","@step1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 1 indicator highlighted\" for \"step progress is highlighted\" in step 1","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 1 indicator highlighted\"","children":[{"start":17,"value":"Step 1 indicator highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"step progress is highlighted\"","children":[{"start":52,"value":"step progress is highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"1","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":29,"pickleLine":28,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@navbloodreportmodal","@step1"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 1 of 5\" for \"progress shows 1 of 5 steps\" in step 1","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 1 of 5\"","children":[{"start":17,"value":"Step 1 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"progress shows 1 of 5 steps\"","children":[{"start":35,"value":"progress shows 1 of 5 steps","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"1","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":37,"pickleLine":38,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1fieldfn"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":39,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Please enter a number.\" for \"alphabets in height field\" for step 1 fields","stepMatchArguments":[{"group":{"start":16,"value":"\"Please enter a number.\"","children":[{"start":17,"value":"Please enter a number.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"alphabets in height field\"","children":[{"start":46,"value":"alphabets in height field","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":82,"value":"1","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":42,"pickleLine":39,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1fieldfn"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":44,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Please enter a number.\" for \"alphabets in weight field\" for step 1 fields","stepMatchArguments":[{"group":{"start":16,"value":"\"Please enter a number.\"","children":[{"start":17,"value":"Please enter a number.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"alphabets in weight field\"","children":[{"start":46,"value":"alphabets in weight field","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":82,"value":"1","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":51,"pickleLine":49,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":53,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Pick your pace: chill stroll or marathon magic\" for \"step 2 title\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Pick your pace: chill stroll or marathon magic\"","children":[{"start":17,"value":"Pick your pace: chill stroll or marathon magic","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"step 2 title\"","children":[{"start":70,"value":"step 2 title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":56,"pickleLine":50,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":58,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Select your preferred exercise intensity level\" for \"step 2 subheading\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Select your preferred exercise intensity level\"","children":[{"start":17,"value":"Select your preferred exercise intensity level","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"step 2 subheading\"","children":[{"start":70,"value":"step 2 subheading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":65,"pickleLine":60,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1tostep2withreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":67,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 2 indicator highlighted\" for \"step progress is highlighted\" in step 2","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 2 indicator highlighted\"","children":[{"start":17,"value":"Step 2 indicator highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"step progress is highlighted\"","children":[{"start":52,"value":"step progress is highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"2","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":70,"pickleLine":61,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1tostep2withreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":72,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 2 of 5\" for \"navigation of step\" in step 2","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 2 of 5\"","children":[{"start":17,"value":"Step 2 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of step\"","children":[{"start":35,"value":"navigation of step","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"2","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":75,"pickleLine":62,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1tostep2withreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":77,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 2 of 5\" for \"progress shows 2 of 5 steps\" in step 2","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 2 of 5\"","children":[{"start":17,"value":"Step 2 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"progress shows 2 of 5 steps\"","children":[{"start":35,"value":"progress shows 2 of 5 steps","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"2","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":80,"pickleLine":63,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step1tostep2withreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":82,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Back\" for \"Back button visibility\" in step 2","stepMatchArguments":[{"group":{"start":16,"value":"\"Back\"","children":[{"start":17,"value":"Back","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"Back button visibility\"","children":[{"start":28,"value":"Back button visibility","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":60,"value":"2","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":87,"pickleLine":67,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2options","@WithReportSteps_13"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":68,"keywordType":"Action","textWithKeyword":"When User clicks continue after entering values in step 1","stepMatchArguments":[{"group":{"start":51,"value":"1","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":89,"gherkinStepLine":69,"keywordType":"Outcome","textWithKeyword":"Then User should see options:","stepMatchArguments":[]}]},
  {"pwTestLine":94,"pickleLine":86,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":80,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":81,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":97,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Your taste buds—what team are they on?\" for \"step 3 title\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Your taste buds—what team are they on?\"","children":[{"start":17,"value":"Your taste buds—what team are they on?","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":61,"value":"\"step 3 title\"","children":[{"start":62,"value":"step 3 title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":100,"pickleLine":87,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":80,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":81,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":103,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Select your dietary preference\" for \"step 3 subheading\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Select your dietary preference\"","children":[{"start":17,"value":"Select your dietary preference","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"step 3 subheading\"","children":[{"start":54,"value":"step 3 subheading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":110,"pickleLine":98,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2tostep3"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":92,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":112,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When User clicks \"Medium 💪\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Medium 💪\"","children":[{"start":13,"value":"Medium 💪","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":113,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 3 of 5\" for \"option selection in step 2\" in step 3","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 3 of 5\"","children":[{"start":17,"value":"Step 3 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"option selection in step 2\"","children":[{"start":35,"value":"option selection in step 2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":71,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":116,"pickleLine":99,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2tostep3"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":117,"gherkinStepLine":92,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":118,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":119,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 3 indicator highlighted\" for \"step progress is highlighted\" in step 3","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 3 indicator highlighted\"","children":[{"start":17,"value":"Step 3 indicator highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"step progress is highlighted\"","children":[{"start":52,"value":"step progress is highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":122,"pickleLine":100,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2tostep3"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":92,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":124,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":125,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 3 of 5\" for \"navigation of step\" in step 3","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 3 of 5\"","children":[{"start":17,"value":"Step 3 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of step\"","children":[{"start":35,"value":"navigation of step","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":128,"pickleLine":101,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2tostep3"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":129,"gherkinStepLine":92,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":131,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 3 of 5\" for \"progress shows 3 of 5 steps\" in step 3","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 3 of 5\"","children":[{"start":17,"value":"Step 3 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"progress shows 3 of 5 steps\"","children":[{"start":35,"value":"progress shows 3 of 5 steps","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":134,"pickleLine":102,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step2tostep3"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":135,"gherkinStepLine":92,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":136,"gherkinStepLine":93,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":137,"gherkinStepLine":94,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Back\" for \"Back button visibility\" in step 3","stepMatchArguments":[{"group":{"start":16,"value":"\"Back\"","children":[{"start":17,"value":"Back","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"Back button visibility\"","children":[{"start":28,"value":"Back button visibility","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":60,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":144,"pickleLine":116,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3options"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":107,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":108,"keywordType":"Action","textWithKeyword":"When User clicks \"Easy 🦋\" from step 2","stepMatchArguments":[{"group":{"start":12,"value":"\"Easy 🦋\"","children":[{"start":13,"value":"Easy 🦋","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"2","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":147,"gherkinStepLine":109,"keywordType":"Outcome","textWithKeyword":"Then User should see options:","stepMatchArguments":[]}]},
  {"pwTestLine":152,"pickleLine":121,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@navbackstep2tostep1","@WithReportSteps_22"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":153,"gherkinStepLine":122,"keywordType":"Context","textWithKeyword":"Given User is in step2 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":154,"gherkinStepLine":123,"keywordType":"Action","textWithKeyword":"When User clicks back button","stepMatchArguments":[]},{"pwStepLine":155,"gherkinStepLine":124,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 1 of 5\" for \"navigation of back button\" in step 2","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 1 of 5\"","children":[{"start":17,"value":"Step 1 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of back button\"","children":[{"start":35,"value":"navigation of back button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":70,"value":"2","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":160,"pickleLine":138,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":161,"gherkinStepLine":132,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":162,"gherkinStepLine":133,"keywordType":"Action","textWithKeyword":"When User clicks \"All-inclusive diet 🍴🍖🍎\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"All-inclusive diet 🍴🍖🍎\"","children":[{"start":13,"value":"All-inclusive diet 🍴🍖🍎","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":163,"gherkinStepLine":134,"keywordType":"Outcome","textWithKeyword":"Then User should see \"What's your go-to food passport?\" for \"step 4 title\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"What's your go-to food passport?\"","children":[{"start":17,"value":"What's your go-to food passport?","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":55,"value":"\"step 4 title\"","children":[{"start":56,"value":"step 4 title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":166,"pickleLine":139,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":167,"gherkinStepLine":132,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":168,"gherkinStepLine":133,"keywordType":"Action","textWithKeyword":"When User clicks \"All-inclusive diet 🍴🍖🍎\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"All-inclusive diet 🍴🍖🍎\"","children":[{"start":13,"value":"All-inclusive diet 🍴🍖🍎","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":169,"gherkinStepLine":134,"keywordType":"Outcome","textWithKeyword":"Then User should see \"To create a meal plan you'll enjoy, please select your preferred cuisines!\" for \"step 4 subheading\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"To create a meal plan you'll enjoy, please select your preferred cuisines!\"","children":[{"start":17,"value":"To create a meal plan you'll enjoy, please select your preferred cuisines!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":97,"value":"\"step 4 subheading\"","children":[{"start":98,"value":"step 4 subheading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":176,"pickleLine":150,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3tostep4"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":177,"gherkinStepLine":144,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":178,"gherkinStepLine":145,"keywordType":"Action","textWithKeyword":"When User clicks \"Vegan 🥬🌱🌿\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"Vegan 🥬🌱🌿\"","children":[{"start":13,"value":"Vegan 🥬🌱🌿","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":179,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 4 of 5\" for \"option selection in step 3\" in step 4","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 4 of 5\"","children":[{"start":17,"value":"Step 4 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"option selection in step 3\"","children":[{"start":35,"value":"option selection in step 3","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":71,"value":"4","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":182,"pickleLine":151,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3tostep4"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":183,"gherkinStepLine":144,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":184,"gherkinStepLine":145,"keywordType":"Action","textWithKeyword":"When User clicks \"Vegan 🥬🌱🌿\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"Vegan 🥬🌱🌿\"","children":[{"start":13,"value":"Vegan 🥬🌱🌿","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":185,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 4 indicator highlighted\" for \"step progress is highlighted\" in step 4","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 4 indicator highlighted\"","children":[{"start":17,"value":"Step 4 indicator highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"step progress is highlighted\"","children":[{"start":52,"value":"step progress is highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"4","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":188,"pickleLine":152,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3tostep4"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":189,"gherkinStepLine":144,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":190,"gherkinStepLine":145,"keywordType":"Action","textWithKeyword":"When User clicks \"Vegan 🥬🌱🌿\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"Vegan 🥬🌱🌿\"","children":[{"start":13,"value":"Vegan 🥬🌱🌿","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":191,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 4 of 5\" for \"navigation of step\" in step 4","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 4 of 5\"","children":[{"start":17,"value":"Step 4 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of step\"","children":[{"start":35,"value":"navigation of step","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"4","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":194,"pickleLine":153,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3tostep4"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":195,"gherkinStepLine":144,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":196,"gherkinStepLine":145,"keywordType":"Action","textWithKeyword":"When User clicks \"Vegan 🥬🌱🌿\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"Vegan 🥬🌱🌿\"","children":[{"start":13,"value":"Vegan 🥬🌱🌿","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":197,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 4 of 5\" for \"progress shows 4 of 5 steps\" in step 4","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 4 of 5\"","children":[{"start":17,"value":"Step 4 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"progress shows 4 of 5 steps\"","children":[{"start":35,"value":"progress shows 4 of 5 steps","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"4","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":200,"pickleLine":154,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step3tostep4"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":201,"gherkinStepLine":144,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":202,"gherkinStepLine":145,"keywordType":"Action","textWithKeyword":"When User clicks \"Vegan 🥬🌱🌿\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"Vegan 🥬🌱🌿\"","children":[{"start":13,"value":"Vegan 🥬🌱🌿","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":203,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Back\" for \"Back button visibility\" in step 4","stepMatchArguments":[{"group":{"start":16,"value":"\"Back\"","children":[{"start":17,"value":"Back","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"Back button visibility\"","children":[{"start":28,"value":"Back button visibility","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":60,"value":"4","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":210,"pickleLine":172,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4options"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":211,"gherkinStepLine":159,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":212,"gherkinStepLine":160,"keywordType":"Action","textWithKeyword":"When User clicks \"All-inclusive diet 🍴🍖🍎\" from step 3","stepMatchArguments":[{"group":{"start":12,"value":"\"All-inclusive diet 🍴🍖🍎\"","children":[{"start":13,"value":"All-inclusive diet 🍴🍖🍎","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"3","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":213,"gherkinStepLine":161,"keywordType":"Outcome","textWithKeyword":"Then User should see options:","stepMatchArguments":[]}]},
  {"pwTestLine":218,"pickleLine":176,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@navbackstep3tostep2","@WithReportSteps_31"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":219,"gherkinStepLine":177,"keywordType":"Context","textWithKeyword":"Given User is in step3 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":220,"gherkinStepLine":178,"keywordType":"Action","textWithKeyword":"When User clicks back button","stepMatchArguments":[]},{"pwStepLine":221,"gherkinStepLine":179,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 2 of 5\" for \"navigation of back button\" in step 3","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 2 of 5\"","children":[{"start":17,"value":"Step 2 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of back button\"","children":[{"start":35,"value":"navigation of back button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":70,"value":"3","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":226,"pickleLine":194,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step5titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":227,"gherkinStepLine":188,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":228,"gherkinStepLine":189,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":229,"gherkinStepLine":190,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Allergic to any foods?\" for \"step 5 title\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Allergic to any foods?\"","children":[{"start":17,"value":"Allergic to any foods?","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"step 5 title\"","children":[{"start":46,"value":"step 5 title","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":232,"pickleLine":195,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step5titleswithreport"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":233,"gherkinStepLine":188,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":234,"gherkinStepLine":189,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":235,"gherkinStepLine":190,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Select all that apply\" for \"step 5 subheading\" in steps","stepMatchArguments":[{"group":{"start":16,"value":"\"Select all that apply\"","children":[{"start":17,"value":"Select all that apply","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"step 5 subheading\"","children":[{"start":45,"value":"step 5 subheading","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":242,"pickleLine":206,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":243,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":244,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":245,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 5 of 5\" for \"option selection in step 4\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 5 of 5\"","children":[{"start":17,"value":"Step 5 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"option selection in step 4\"","children":[{"start":35,"value":"option selection in step 4","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":71,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":248,"pickleLine":207,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":249,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":250,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":251,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 5 indicator highlighted\" for \"step progress is highlighted\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 5 indicator highlighted\"","children":[{"start":17,"value":"Step 5 indicator highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"step progress is highlighted\"","children":[{"start":52,"value":"step progress is highlighted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":254,"pickleLine":208,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":255,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":256,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":257,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 5 of 5\" for \"navigation of step\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 5 of 5\"","children":[{"start":17,"value":"Step 5 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of step\"","children":[{"start":35,"value":"navigation of step","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":260,"pickleLine":209,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":261,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":262,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":263,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 5 of 5\" for \"progress shows 5 of 5 steps\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 5 of 5\"","children":[{"start":17,"value":"Step 5 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"progress shows 5 of 5 steps\"","children":[{"start":35,"value":"progress shows 5 of 5 steps","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":72,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":266,"pickleLine":210,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":267,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":268,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":269,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Back\" for \"Back button visibility\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Back\"","children":[{"start":17,"value":"Back","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"Back button visibility\"","children":[{"start":28,"value":"Back button visibility","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":60,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":272,"pickleLine":211,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":273,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":274,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":275,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Submit\" for \"Submit button visibility\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Submit\"","children":[{"start":17,"value":"Submit","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":29,"value":"\"Submit button visibility\"","children":[{"start":30,"value":"Submit button visibility","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":64,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":278,"pickleLine":212,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step4tostep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":279,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":280,"gherkinStepLine":201,"keywordType":"Action","textWithKeyword":"When User clicks \"Indian 🍛\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Indian 🍛\"","children":[{"start":13,"value":"Indian 🍛","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":281,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Check box\" for \"Checkbox for options\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Check box\"","children":[{"start":17,"value":"Check box","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":32,"value":"\"Checkbox for options\"","children":[{"start":33,"value":"Checkbox for options","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":288,"pickleLine":231,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@step5options"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":289,"gherkinStepLine":217,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":290,"gherkinStepLine":218,"keywordType":"Action","textWithKeyword":"When User clicks \"Asian 🍜\" from step 4","stepMatchArguments":[{"group":{"start":12,"value":"\"Asian 🍜\"","children":[{"start":13,"value":"Asian 🍜","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":33,"value":"4","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":291,"gherkinStepLine":219,"keywordType":"Outcome","textWithKeyword":"Then User should see options:","stepMatchArguments":[]}]},
  {"pwTestLine":296,"pickleLine":235,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@navbackstep4tostep3","@WithReportSteps_42"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":297,"gherkinStepLine":236,"keywordType":"Context","textWithKeyword":"Given User is in step4 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":298,"gherkinStepLine":237,"keywordType":"Action","textWithKeyword":"When User clicks back button","stepMatchArguments":[]},{"pwStepLine":299,"gherkinStepLine":238,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 3 of 5\" for \"navigation of back button\" in step 4","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 3 of 5\"","children":[{"start":17,"value":"Step 3 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of back button\"","children":[{"start":35,"value":"navigation of back button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":70,"value":"4","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":302,"pickleLine":247,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@navbackstep5tostep4","@WithReportSteps_43"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":303,"gherkinStepLine":248,"keywordType":"Context","textWithKeyword":"Given User is in step5 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":304,"gherkinStepLine":249,"keywordType":"Action","textWithKeyword":"When User clicks back button","stepMatchArguments":[]},{"pwStepLine":305,"gherkinStepLine":250,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Step 4 of 5\" for \"navigation of back button\" in step 5","stepMatchArguments":[{"group":{"start":16,"value":"\"Step 4 of 5\"","children":[{"start":17,"value":"Step 4 of 5","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":34,"value":"\"navigation of back button\"","children":[{"start":35,"value":"navigation of back button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":70,"value":"5","children":[]},"parameterTypeName":"int"}]}]},
  {"pwTestLine":310,"pickleLine":261,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@selectionstep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":311,"gherkinStepLine":255,"keywordType":"Context","textWithKeyword":"Given User is in step5 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":312,"gherkinStepLine":256,"keywordType":"Action","textWithKeyword":"When User selects \"Gluten 🥖🍞, Dairy 🐄🥛,  Nuts 🌰🥜\" and clicks submit from step 5","stepMatchArguments":[{"group":{"start":13,"value":"\"Gluten 🥖🍞, Dairy 🐄🥛,  Nuts 🌰🥜\"","children":[{"start":14,"value":"Gluten 🥖🍞, Dairy 🐄🥛,  Nuts 🌰🥜","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"5","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":313,"gherkinStepLine":257,"keywordType":"Outcome","textWithKeyword":"Then User should be navigated to free and premium details page","stepMatchArguments":[]}]},
  {"pwTestLine":316,"pickleLine":262,"tags":["@sweet","@withreportsteps","@skiplogin","@register","@ela","@selectionstep5"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on report analysis and uploads the file","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks Onboarding button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":317,"gherkinStepLine":255,"keywordType":"Context","textWithKeyword":"Given User is in step5 of onboarding with report","stepMatchArguments":[]},{"pwStepLine":318,"gherkinStepLine":256,"keywordType":"Action","textWithKeyword":"When User selects \"Gluten 🥖🍞\" and clicks submit from step 5","stepMatchArguments":[{"group":{"start":13,"value":"\"Gluten 🥖🍞\"","children":[{"start":14,"value":"Gluten 🥖🍞","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":55,"value":"5","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":319,"gherkinStepLine":257,"keywordType":"Outcome","textWithKeyword":"Then User should be navigated to free and premium details page","stepMatchArguments":[]}]},
]; // bdd-data-end