// Generated from: featureFiles\DashboardPage\CommonFeaturesDashboard.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Dashboard page validation for Registered Free account user', () => {

  test.beforeEach('Background', async ({ Given, When, pages }, testInfo) => { if (testInfo.error) return;
    await Given('User is in Home Page', null, { pages }); 
    await When('User clicks the Dashboard on the navigation bar', null, { pages }); 
  });
  
  test.describe('Verify <Scenario> on Dashboard page', () => {

    test('Verify WelcomeMesg on Dashboard page', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Welcome Back," for "WelcomeMesg"', null, { pages }); 
    });

    test('Verify subtext on Dashboard page', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Track your metrics, manage your diet, and stay healthy with our comprehensive tools." for "subtext"', null, { pages }); 
    });

  });

  test('Verify action buttons visibility on Dashboard page', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_02', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following buttons on Dashboard page', {"dataTable":{"rows":[{"cells":[{"value":"Upgrade to Premium"}]},{"cells":[{"value":"Save Changes"}]}]}}, { pages }); 
  });

  test('Verify Account Information header is present', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_03', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the header "Account Information" with correct spelling', null, { pages }); 
  });

  test.describe('Verify all fields under Account Information section are displayed', () => {

    test('Example #1', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_04', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Age" field under Account Information section', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_04', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Weight(kg)" field under Account Information section', null, { pages }); 
    });

    test('Example #3', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_04', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Cuisine Preferences" field under Account Information section', null, { pages }); 
    });

    test('Example #4', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_04', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Food Allergies" field under Account Information section', null, { pages }); 
    });

    test('Example #5', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_04', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Height(cm)" field under Account Information section', null, { pages }); 
    });

    test('Example #6', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_04', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see the "Exercise Routine Level" field under Account Information section', null, { pages }); 
    });

  });

  test('Verify Exercise Routine Level dropdown options', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_05', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is in dashboard Page', null, { pages }); 
    await When('User clicks the "Exercise Routine Level" dropdown', null, { pages }); 
    await Then('User should see the dropdown options', {"dataTable":{"rows":[{"cells":[{"value":"Easy"}]},{"cells":[{"value":"Medium"}]},{"cells":[{"value":"Hard"}]}]}}, { pages }); 
  });

  test('Verify Cuisine Preferences dropdown options', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_06', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is in dashboard Page', null, { pages }); 
    await When('User clicks the "Cuisine Preferences" dropdown', null, { pages }); 
    await Then('User should see the dropdown options', {"dataTable":{"rows":[{"cells":[{"value":"Indian"}]},{"cells":[{"value":"American"}]},{"cells":[{"value":"Continental"}]},{"cells":[{"value":"Mediterranean"}]},{"cells":[{"value":"Asian"}]},{"cells":[{"value":"Middle Eastern"}]},{"cells":[{"value":"Mexican"}]}]}}, { pages }); 
  });

  test('Verify Food Allergies dropdown options', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_07', '@FunctionalValidation'] }, async ({ When, Then, pages }) => { 
    await When('User clicks the "Food Allergies" dropdown', null, { pages }); 
    await Then('User should see the dropdown options', {"dataTable":{"rows":[{"cells":[{"value":"None"}]},{"cells":[{"value":"Dairy"}]},{"cells":[{"value":"Gluten"}]},{"cells":[{"value":"Shellfish"}]},{"cells":[{"value":"Soy"}]},{"cells":[{"value":"Eggs"}]},{"cells":[{"value":"Nuts"}]},{"cells":[{"value":"Other"}]}]}}, { pages }); 
  });

  test.describe('Verify <Scenario> value is rejected in age field', () => {

    test('Verify alphabet value is rejected in age field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_08', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User edit "age" field with "alphabet"', null, { pages, testData }); 
      await Then('User should see an "age" field remain blank', null, { pages }); 
    });

    test('Verify special char value is rejected in age field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_08', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User edit "age" field with "special char"', null, { pages, testData }); 
      await Then('User should see an "age" field remain blank', null, { pages }); 
    });

    test('Verify negative value is rejected in age field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_08', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User edit "age" field with "negative"', null, { pages, testData }); 
      await Then('User should see an "age" field remain blank', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> value is rejected in height field', () => {

    test('Verify alphabet value is rejected in height field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_09', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User edit "Height" field with "alphabet"', null, { pages, testData }); 
      await Then('User should see an "Height" field remain blank', null, { pages }); 
    });

    test('Verify special char value is rejected in height field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_09', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User edit "Height" field with "special char"', null, { pages, testData }); 
      await Then('User should see an "Height" field remain blank', null, { pages }); 
    });

    test('Verify negative value is rejected in height field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_09', '@FunctionalValidation', '@negative'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User edit "Height" field with "negative"', null, { pages, testData }); 
      await Then('User should see an "Height" field remain blank', null, { pages }); 
    });

  });

  test.describe('Verify <Scenario> value is rejected in weight field', () => {

    test('Verify alphabet value is rejected in weight field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_10', '@FunctionalValidation', '@negative'] }, async ({ When, Then, pages, testData }) => { 
      await When('User edit "Weight" field with "alphabet"', null, { pages, testData }); 
      await Then('User should see an "Weight" field remain blank', null, { pages }); 
    });

    test('Verify special char value is rejected in weight field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_10', '@FunctionalValidation', '@negative'] }, async ({ When, Then, pages, testData }) => { 
      await When('User edit "Weight" field with "special char"', null, { pages, testData }); 
      await Then('User should see an "Weight" field remain blank', null, { pages }); 
    });

    test('Verify negative value is rejected in weight field', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_10', '@FunctionalValidation', '@negative'] }, async ({ When, Then, pages, testData }) => { 
      await When('User edit "Weight" field with "negative"', null, { pages, testData }); 
      await Then('User should see an "Weight" field remain blank', null, { pages }); 
    });

  });

  test.describe('Verify account details can be updated with <Scenario>', () => {

    test('Verify account details can be updated with valid data', { tag: ['@sweetBalance', '@DashboardPage', '@loginfree', '@DashboardPage_11', '@FunctionalValidation', '@positive'] }, async ({ When, Then, pages, testData }) => { 
      await When('User clicks save button after editing field with valid data', null, { pages, testData }); 
      await Then('User should see messages "Changes SavedYour profile has been updated successfully!"', null, { pages }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles\\DashboardPage\\CommonFeaturesDashboard.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":14,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Welcome Back,\" for \"WelcomeMesg\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Welcome Back,\"","children":[{"start":21,"value":"Welcome Back,","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"WelcomeMesg\"","children":[{"start":41,"value":"WelcomeMesg","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":15,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Track your metrics, manage your diet, and stay healthy with our comprehensive tools.\" for \"subtext\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Track your metrics, manage your diet, and stay healthy with our comprehensive tools.\"","children":[{"start":21,"value":"Track your metrics, manage your diet, and stay healthy with our comprehensive tools.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":111,"value":"\"subtext\"","children":[{"start":112,"value":"subtext","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":18,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_02","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then User should see the following buttons on Dashboard page","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":24,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_03","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then User should see the header \"Account Information\" with correct spelling","stepMatchArguments":[{"group":{"start":27,"value":"\"Account Information\"","children":[{"start":28,"value":"Account Information","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":33,"pickleLine":33,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Age\" field under Account Information section","stepMatchArguments":[{"group":{"start":20,"value":"\"Age\"","children":[{"start":21,"value":"Age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":37,"pickleLine":34,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Weight(kg)\" field under Account Information section","stepMatchArguments":[{"group":{"start":20,"value":"\"Weight(kg)\"","children":[{"start":21,"value":"Weight(kg)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":41,"pickleLine":35,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Cuisine Preferences\" field under Account Information section","stepMatchArguments":[{"group":{"start":20,"value":"\"Cuisine Preferences\"","children":[{"start":21,"value":"Cuisine Preferences","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":45,"pickleLine":36,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Food Allergies\" field under Account Information section","stepMatchArguments":[{"group":{"start":20,"value":"\"Food Allergies\"","children":[{"start":21,"value":"Food Allergies","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":37,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Height(cm)\" field under Account Information section","stepMatchArguments":[{"group":{"start":20,"value":"\"Height(cm)\"","children":[{"start":21,"value":"Height(cm)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":53,"pickleLine":38,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Exercise Routine Level\" field under Account Information section","stepMatchArguments":[{"group":{"start":20,"value":"\"Exercise Routine Level\"","children":[{"start":21,"value":"Exercise Routine Level","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":59,"pickleLine":42,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_05","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When User clicks the \"Exercise Routine Level\" dropdown","stepMatchArguments":[{"group":{"start":16,"value":"\"Exercise Routine Level\"","children":[{"start":17,"value":"Exercise Routine Level","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then User should see the dropdown options","stepMatchArguments":[]}]},
  {"pwTestLine":65,"pickleLine":51,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_06","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":52,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When User clicks the \"Cuisine Preferences\" dropdown","stepMatchArguments":[{"group":{"start":16,"value":"\"Cuisine Preferences\"","children":[{"start":17,"value":"Cuisine Preferences","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then User should see the dropdown options","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":64,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_07","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":65,"keywordType":"Action","textWithKeyword":"When User clicks the \"Food Allergies\" dropdown","stepMatchArguments":[{"group":{"start":16,"value":"\"Food Allergies\"","children":[{"start":17,"value":"Food Allergies","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then User should see the dropdown options","stepMatchArguments":[]}]},
  {"pwTestLine":78,"pickleLine":84,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_08","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User edit \"age\" field with \"alphabet\"","stepMatchArguments":[{"group":{"start":10,"value":"\"age\"","children":[{"start":11,"value":"age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"alphabet\"","children":[{"start":28,"value":"alphabet","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"age\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"age\"","children":[{"start":20,"value":"age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":84,"pickleLine":85,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_08","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":85,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User edit \"age\" field with \"special char\"","stepMatchArguments":[{"group":{"start":10,"value":"\"age\"","children":[{"start":11,"value":"age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"special char\"","children":[{"start":28,"value":"special char","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"age\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"age\"","children":[{"start":20,"value":"age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":90,"pickleLine":86,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_08","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":92,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When User edit \"age\" field with \"negative\"","stepMatchArguments":[{"group":{"start":10,"value":"\"age\"","children":[{"start":11,"value":"age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"negative\"","children":[{"start":28,"value":"negative","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"age\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"age\"","children":[{"start":20,"value":"age","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":100,"pickleLine":96,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_09","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When User edit \"Height\" field with \"alphabet\"","stepMatchArguments":[{"group":{"start":10,"value":"\"Height\"","children":[{"start":11,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"alphabet\"","children":[{"start":31,"value":"alphabet","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":103,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"Height\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Height\"","children":[{"start":20,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":106,"pickleLine":97,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_09","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":108,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When User edit \"Height\" field with \"special char\"","stepMatchArguments":[{"group":{"start":10,"value":"\"Height\"","children":[{"start":11,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"special char\"","children":[{"start":31,"value":"special char","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"Height\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Height\"","children":[{"start":20,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":112,"pickleLine":98,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_09","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":113,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":114,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When User edit \"Height\" field with \"negative\"","stepMatchArguments":[{"group":{"start":10,"value":"\"Height\"","children":[{"start":11,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"negative\"","children":[{"start":31,"value":"negative","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":115,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"Height\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Height\"","children":[{"start":20,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":122,"pickleLine":107,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_10","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":102,"keywordType":"Action","textWithKeyword":"When User edit \"Weight\" field with \"alphabet\"","stepMatchArguments":[{"group":{"start":10,"value":"\"Weight\"","children":[{"start":11,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"alphabet\"","children":[{"start":31,"value":"alphabet","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":124,"gherkinStepLine":103,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"Weight\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Weight\"","children":[{"start":20,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":127,"pickleLine":108,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_10","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":128,"gherkinStepLine":102,"keywordType":"Action","textWithKeyword":"When User edit \"Weight\" field with \"special char\"","stepMatchArguments":[{"group":{"start":10,"value":"\"Weight\"","children":[{"start":11,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"special char\"","children":[{"start":31,"value":"special char","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":103,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"Weight\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Weight\"","children":[{"start":20,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":132,"pickleLine":109,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_10","@FunctionalValidation","@negative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":102,"keywordType":"Action","textWithKeyword":"When User edit \"Weight\" field with \"negative\"","stepMatchArguments":[{"group":{"start":10,"value":"\"Weight\"","children":[{"start":11,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"negative\"","children":[{"start":31,"value":"negative","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":103,"keywordType":"Outcome","textWithKeyword":"Then User should see an \"Weight\" field remain blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Weight\"","children":[{"start":20,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":141,"pickleLine":118,"tags":["@sweetBalance","@DashboardPage","@loginfree","@DashboardPage_11","@FunctionalValidation","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":142,"gherkinStepLine":113,"keywordType":"Action","textWithKeyword":"When User clicks save button after editing field with valid data","stepMatchArguments":[]},{"pwStepLine":143,"gherkinStepLine":114,"keywordType":"Outcome","textWithKeyword":"Then User should see messages \"Changes SavedYour profile has been updated successfully!\"","stepMatchArguments":[{"group":{"start":25,"value":"\"Changes SavedYour profile has been updated successfully!\"","children":[{"start":26,"value":"Changes SavedYour profile has been updated successfully!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end