// Generated from: featureFiles/DashboardPage/PremiumAdditionalDashboard.feature
import { test } from "../../../fixtures/Index_Fixture.js";

test.describe('Additional Dashboard page validation for Registered Premium account user', () => {

  test.beforeEach('Background: User is in Home Page after logged in', async ({ Given, When, pages }, testInfo) => { if (testInfo.error) return;
    await Given('User is in Home Page', null, { pages }); 
    await When('User clicks the Dashboard on the navigation bar', null, { pages }); 
  });
  
  test.describe('Verify premium user indicators on dashboard', () => {

    test('Example #1', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "👑 Premium Activated" displayed', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_01', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Manage Premium" displayed', null, { pages }); 
    });

  });

  test('Verify Manage Premium button is clickable', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_02', '@FunctionalValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is in dashboard Page', null, { pages }); 
    await When('User clicks the "Manage Premium" button in dashboard page', null, { pages }); 
    await Then('User should see the premium subscription dialog box', null, { pages }); 
  });

  test.describe('Verify premium subscription dates are displayed', () => {

    test('Example #1', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_03', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "Start Date:" with value in format "EEE, MMM dd, yyyy"', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_03', '@UIValidation'] }, async ({ Then, pages }) => { 
      await Then('User should see "End Date:" with value in format "EEE, MMM dd, yyyy"', null, { pages }); 
    });

  });

  test('Verify Emotional Wellbeing section title', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_04', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is in dashboard Page', null, { pages }); 
    await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
    await Then('User should see the title "😊 Emotional Wellbeing" in dashboard page', null, { pages }); 
  });

  test.describe('Verify Emotional Wellbeing UI elements', () => {

    test('Example #1', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_05', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
      await Then('User should see "How are you feeling today?" in Emotional Wellbeing section', null, { pages }); 
    });

    test('Example #2', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_05', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
      await Then('User should see "Notes on your mood" in Emotional Wellbeing section', null, { pages }); 
    });

    test('Example #3', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_05', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
      await Then('User should see "What\'s affecting your mood today?" in Emotional Wellbeing section', null, { pages }); 
    });

    test('Example #4', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_05', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
      await Then('User should see "Energy level slider" in Emotional Wellbeing section', null, { pages }); 
    });

    test('Example #5', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_05', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
      await Then('User should see "Log emotional state button" in Emotional Wellbeing section', null, { pages }); 
    });

  });

  test('Verify mood emojis are displayed', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_06', '@UIValidation'] }, async ({ Given, When, Then, pages }) => { 
    await Given('User is in dashboard Page', null, { pages }); 
    await When('User scrolls to the middle of the Dashboard page', null, { pages }); 
    await Then('User should see the following mood emojis "😄😊😐😔😠😰"', null, { pages }); 
  });

  test('Verify the text under energy slider', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_07', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see Energy level slider with labels "low" and "high"', null, { pages }); 
  });

  test.describe('Verify user can enter <Scenario> on mood', () => {

    test('Verify user can enter notes on mood', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_08', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User enters text in notes on your mood field', null, { pages, testData }); 
      await Then('User should see the entered value in the input field', null, { pages, testData }); 
    });

  });

  test.describe('Verify energy level slider changes value for <Scenario>', () => {

    test('Verify energy level slider changes value for moving left', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_09', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User moves the energy level slider to "moving left"', null, { pages, testData }); 
      await Then('User should see the energy value change accordingly for "moving left"', null, { pages, testData }); 
    });

    test('Verify energy level slider changes value for moving right', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_09', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User moves the energy level slider to "moving right"', null, { pages, testData }); 
      await Then('User should see the energy value change accordingly for "moving right"', null, { pages, testData }); 
    });

  });

  test.describe('Verify emotional state for <Scenario> is logged successfully', () => {

    test('Verify emotional state for Happy is logged successfully', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_10', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User clicks log emotional state after selecting a "Happy" mood emoji', null, { pages, testData }); 
      await Then('User should see the message "Your emotional state has been recorded successfully."', null, { pages }); 
    });

    test('Verify emotional state for Content is logged successfully', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_10', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User clicks log emotional state after selecting a "Content" mood emoji', null, { pages, testData }); 
      await Then('User should see the message "Your emotional state has been recorded successfully."', null, { pages }); 
    });

    test('Verify emotional state for Neutral is logged successfully', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_10', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User clicks log emotional state after selecting a "Neutral" mood emoji', null, { pages, testData }); 
      await Then('User should see the message "Your emotional state has been recorded successfully."', null, { pages }); 
    });

    test('Verify emotional state for Sad is logged successfully', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_10', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User clicks log emotional state after selecting a "Sad" mood emoji', null, { pages, testData }); 
      await Then('User should see the message "Your emotional state has been recorded successfully."', null, { pages }); 
    });

    test('Verify emotional state for Angry is logged successfully', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_10', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User clicks log emotional state after selecting a "Angry" mood emoji', null, { pages, testData }); 
      await Then('User should see the message "Your emotional state has been recorded successfully."', null, { pages }); 
    });

    test('Verify emotional state for Anxious is logged successfully', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_10', '@FunctionalValidation'] }, async ({ Given, When, Then, pages, testData }) => { 
      await Given('User is in dashboard Page', null, { pages }); 
      await When('User clicks log emotional state after selecting a "Anxious" mood emoji', null, { pages, testData }); 
      await Then('User should see the message "Your emotional state has been recorded successfully."', null, { pages }); 
    });

  });

  test('Verify Smart Insights section on Premium dashboard', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_11', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see Smart Insights section with the following details:', {"dataTable":{"rows":[{"cells":[{"value":"Element"}]},{"cells":[{"value":"Title"}]},{"cells":[{"value":"Label"}]}]}}, { pages }); 
  });

  test('Verify Smart Insights titles on Premium dashboard', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_12', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following Smart Insights titles:', {"dataTable":{"rows":[{"cells":[{"value":"Target Achievement"}]},{"cells":[{"value":"Pattern Detected"}]},{"cells":[{"value":"Suggestion"}]}]}}, { pages }); 
  });

  test('Verify Smart Insights titles content on Premium dashboard', { tag: ['@sweetBalance', '@DashboardPagePremium', '@run', '@DashboardPage_Premium_13', '@UIValidation'] }, async ({ Then, pages }) => { 
    await Then('User should see the following "Content" under Smart Insights "Titles":', {"dataTable":{"rows":[{"cells":[{"value":"Titles"},{"value":"Content"}]},{"cells":[{"value":"Target Achievement"},{"value":"percentage of time the user was in the target range for the last 7 days with the percentage improvement compared to the previous week"}]},{"cells":[{"value":"Pattern Detected"},{"value":"percentage of glucose value spike with suggestion to improve"}]},{"cells":[{"value":"Suggestion"},{"value":"suggestion of activity with the average expected glucose reduction from this activity"}]}]}}, { pages }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('featureFiles/DashboardPage/PremiumAdditionalDashboard.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":14,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"👑 Premium Activated\" displayed","stepMatchArguments":[{"group":{"start":16,"value":"\"👑 Premium Activated\"","children":[{"start":17,"value":"👑 Premium Activated","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":15,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_01","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Manage Premium\" displayed","stepMatchArguments":[{"group":{"start":16,"value":"\"Manage Premium\"","children":[{"start":17,"value":"Manage Premium","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":18,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_02","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":19,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":20,"keywordType":"Action","textWithKeyword":"When User clicks the \"Manage Premium\" button in dashboard page","stepMatchArguments":[{"group":{"start":16,"value":"\"Manage Premium\"","children":[{"start":17,"value":"Manage Premium","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":21,"keywordType":"Outcome","textWithKeyword":"Then User should see the premium subscription dialog box","stepMatchArguments":[]}]},
  {"pwTestLine":31,"pickleLine":29,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_03","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Start Date:\" with value in format \"EEE, MMM dd, yyyy\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Start Date:\"","children":[{"start":17,"value":"Start Date:","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"EEE, MMM dd, yyyy\"","children":[{"start":52,"value":"EEE, MMM dd, yyyy","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":35,"pickleLine":30,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_03","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then User should see \"End Date:\" with value in format \"EEE, MMM dd, yyyy\"","stepMatchArguments":[{"group":{"start":16,"value":"\"End Date:\"","children":[{"start":17,"value":"End Date:","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":49,"value":"\"EEE, MMM dd, yyyy\"","children":[{"start":50,"value":"EEE, MMM dd, yyyy","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":41,"pickleLine":34,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_04","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":35,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then User should see the title \"😊 Emotional Wellbeing\" in dashboard page","stepMatchArguments":[{"group":{"start":26,"value":"\"😊 Emotional Wellbeing\"","children":[{"start":27,"value":"😊 Emotional Wellbeing","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":47,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then User should see \"How are you feeling today?\" in Emotional Wellbeing section","stepMatchArguments":[{"group":{"start":16,"value":"\"How are you feeling today?\"","children":[{"start":17,"value":"How are you feeling today?","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":48,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Notes on your mood\" in Emotional Wellbeing section","stepMatchArguments":[{"group":{"start":16,"value":"\"Notes on your mood\"","children":[{"start":17,"value":"Notes on your mood","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":61,"pickleLine":49,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then User should see \"What's affecting your mood today?\" in Emotional Wellbeing section","stepMatchArguments":[{"group":{"start":16,"value":"\"What's affecting your mood today?\"","children":[{"start":17,"value":"What's affecting your mood today?","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":67,"pickleLine":50,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":70,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Energy level slider\" in Emotional Wellbeing section","stepMatchArguments":[{"group":{"start":16,"value":"\"Energy level slider\"","children":[{"start":17,"value":"Energy level slider","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":73,"pickleLine":51,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_05","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then User should see \"Log emotional state button\" in Emotional Wellbeing section","stepMatchArguments":[{"group":{"start":16,"value":"\"Log emotional state button\"","children":[{"start":17,"value":"Log emotional state button","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":81,"pickleLine":54,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_06","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":82,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"When User scrolls to the middle of the Dashboard page","stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"Then User should see the following mood emojis \"😄😊😐😔😠😰\"","stepMatchArguments":[{"group":{"start":42,"value":"\"😄😊😐😔😠😰\"","children":[{"start":43,"value":"😄😊😐😔😠😰","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":87,"pickleLine":60,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_07","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then User should see Energy level slider with labels \"low\" and \"high\"","stepMatchArguments":[{"group":{"start":48,"value":"\"low\"","children":[{"start":49,"value":"low","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":58,"value":"\"high\"","children":[{"start":59,"value":"high","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":93,"pickleLine":70,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_08","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":94,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When User enters text in notes on your mood field","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then User should see the entered value in the input field","stepMatchArguments":[]}]},
  {"pwTestLine":103,"pickleLine":79,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_09","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":104,"gherkinStepLine":74,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":75,"keywordType":"Action","textWithKeyword":"When User moves the energy level slider to \"moving left\"","stepMatchArguments":[{"group":{"start":38,"value":"\"moving left\"","children":[{"start":39,"value":"moving left","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"Then User should see the energy value change accordingly for \"moving left\"","stepMatchArguments":[{"group":{"start":56,"value":"\"moving left\"","children":[{"start":57,"value":"moving left","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":109,"pickleLine":80,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_09","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":74,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":75,"keywordType":"Action","textWithKeyword":"When User moves the energy level slider to \"moving right\"","stepMatchArguments":[{"group":{"start":38,"value":"\"moving right\"","children":[{"start":39,"value":"moving right","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":112,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"Then User should see the energy value change accordingly for \"moving right\"","stepMatchArguments":[{"group":{"start":56,"value":"\"moving right\"","children":[{"start":57,"value":"moving right","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":119,"pickleLine":90,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_10","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":120,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":121,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When User clicks log emotional state after selecting a \"Happy\" mood emoji","stepMatchArguments":[{"group":{"start":50,"value":"\"Happy\"","children":[{"start":51,"value":"Happy","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":122,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then User should see the message \"Your emotional state has been recorded successfully.\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Your emotional state has been recorded successfully.\"","children":[{"start":29,"value":"Your emotional state has been recorded successfully.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":125,"pickleLine":91,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_10","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":126,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":127,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When User clicks log emotional state after selecting a \"Content\" mood emoji","stepMatchArguments":[{"group":{"start":50,"value":"\"Content\"","children":[{"start":51,"value":"Content","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":128,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then User should see the message \"Your emotional state has been recorded successfully.\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Your emotional state has been recorded successfully.\"","children":[{"start":29,"value":"Your emotional state has been recorded successfully.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":131,"pickleLine":92,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_10","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When User clicks log emotional state after selecting a \"Neutral\" mood emoji","stepMatchArguments":[{"group":{"start":50,"value":"\"Neutral\"","children":[{"start":51,"value":"Neutral","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then User should see the message \"Your emotional state has been recorded successfully.\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Your emotional state has been recorded successfully.\"","children":[{"start":29,"value":"Your emotional state has been recorded successfully.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":137,"pickleLine":93,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_10","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":138,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":139,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When User clicks log emotional state after selecting a \"Sad\" mood emoji","stepMatchArguments":[{"group":{"start":50,"value":"\"Sad\"","children":[{"start":51,"value":"Sad","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":140,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then User should see the message \"Your emotional state has been recorded successfully.\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Your emotional state has been recorded successfully.\"","children":[{"start":29,"value":"Your emotional state has been recorded successfully.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":143,"pickleLine":94,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_10","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When User clicks log emotional state after selecting a \"Angry\" mood emoji","stepMatchArguments":[{"group":{"start":50,"value":"\"Angry\"","children":[{"start":51,"value":"Angry","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":146,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then User should see the message \"Your emotional state has been recorded successfully.\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Your emotional state has been recorded successfully.\"","children":[{"start":29,"value":"Your emotional state has been recorded successfully.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":149,"pickleLine":95,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_10","@FunctionalValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":150,"gherkinStepLine":84,"keywordType":"Context","textWithKeyword":"Given User is in dashboard Page","stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When User clicks log emotional state after selecting a \"Anxious\" mood emoji","stepMatchArguments":[{"group":{"start":50,"value":"\"Anxious\"","children":[{"start":51,"value":"Anxious","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":152,"gherkinStepLine":86,"keywordType":"Outcome","textWithKeyword":"Then User should see the message \"Your emotional state has been recorded successfully.\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Your emotional state has been recorded successfully.\"","children":[{"start":29,"value":"Your emotional state has been recorded successfully.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":157,"pickleLine":99,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_11","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":158,"gherkinStepLine":100,"keywordType":"Outcome","textWithKeyword":"Then User should see Smart Insights section with the following details:","stepMatchArguments":[]}]},
  {"pwTestLine":161,"pickleLine":106,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_12","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":162,"gherkinStepLine":107,"keywordType":"Outcome","textWithKeyword":"Then User should see the following Smart Insights titles:","stepMatchArguments":[]}]},
  {"pwTestLine":165,"pickleLine":113,"tags":["@sweetBalance","@DashboardPagePremium","@run","@DashboardPage_Premium_13","@UIValidation"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is in Home Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Dashboard on the navigation bar","isBg":true,"stepMatchArguments":[]},{"pwStepLine":166,"gherkinStepLine":114,"keywordType":"Outcome","textWithKeyword":"Then User should see the following \"Content\" under Smart Insights \"Titles\":","stepMatchArguments":[{"group":{"start":30,"value":"\"Content\"","children":[{"start":31,"value":"Content","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":61,"value":"\"Titles\"","children":[{"start":62,"value":"Titles","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end